using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using Geta.Epi.FontThumbnail.EnumGenerator.Models;
using Newtonsoft.Json;

namespace Geta.Epi.FontThumbnail.EnumGenerator
{
    internal static class Program
    {
        private static void Main(string[] args)
        {
            var sourcePath = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.FullName;

            Console.WriteLine("Font Awesome Enum Generator");
            Console.WriteLine("{0}", sourcePath);
            var enumBasePath = $@"{sourcePath}\Geta.Epi.FontThumbnail";
            Console.WriteLine("\nOutput directory: {0}", enumBasePath);

AskForFontAwesomeDirectory:
            Console.WriteLine("\nEnter the Font Awesome directory:");
            var fontAwesomePath = Console.ReadLine();
            if (!Directory.Exists(fontAwesomePath))
            {
                Console.WriteLine("\nDirectory does not exist.");
                goto AskForFontAwesomeDirectory;
            }

            var metadataPath = $@"{fontAwesomePath}\metadata\icons.json";
            if (!File.Exists(metadataPath))
            {
                Console.WriteLine("\nDirectory does not contain a metadata directory with a icons.json file.");
                goto AskForFontAwesomeDirectory;
            }

            Console.WriteLine("\nLoading metadata from: {0}", metadataPath);
            var metadata = LoadMetadata(metadataPath);

            // Get a list all the different styles
            var styles = metadata.SelectMany(x => x.Styles).Distinct();

            foreach (var item in styles)
            {
                var styleName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(item);
                var enumName = $"FontAwesome5{styleName}";
                var localPath = $@"{enumBasePath}\{enumName}.cs";

                Console.WriteLine("\nGenerating {0}.cs...", enumName);
                var icons = metadata.Where(x => x.Styles.Contains(item) && !x.Private);
                WriteEnumToFile(localPath, enumName, icons);
            }

            CopyFontFiles(fontAwesomePath, enumBasePath);

            Console.WriteLine("\nDone generating Enums. Press enter to exit.");
            Console.ReadLine();
        }

        private static void CopyFontFiles(string fontAwesomePath, string enumBasePath)
        {
            var source = $@"{fontAwesomePath}\webfonts\";
            var destination = $@"{enumBasePath}\Fonts\";

            var filesToCopy = Directory.GetFiles(source, "*.ttf");
            foreach (var fileToCopy in filesToCopy)
            {
                Console.WriteLine("\nCopying {0} to {1}...", fileToCopy, destination);
                File.Copy(fileToCopy, destination + Path.GetFileName(fileToCopy), true);
            }
        }

        private static IList<MetadataIcon> LoadMetadata(string path)
        {
            using (var file = File.OpenText(path))
            {
                var serializer = new JsonSerializer();
                serializer.Converters.Add(new FontAwesomeJsonConverter());
                return (List<MetadataIcon>)serializer.Deserialize(file, typeof(List<MetadataIcon>));
            }
        }

        private static void WriteEnumToFile(string path, string enumName, IEnumerable<MetadataIcon> icons)
        {
            var latestVersionChange = icons.SelectMany(x => x.Changes).Distinct().OrderBy(x => x).Last();

            using (var writer = new StreamWriter(path))
            {
                writer.WriteLine("//------------------------------------------------------------------------------");
                writer.WriteLine("// <auto-generated>");
                writer.WriteLine("//     This code was generated by a tool.");
                writer.WriteLine("//");
                writer.WriteLine("//     Changes to this file may cause incorrect behavior and will be lost if");
                writer.WriteLine("//     the code is regenerated.");
                writer.WriteLine("// </auto-generated>");
                writer.WriteLine("//------------------------------------------------------------------------------");
                writer.WriteLine();

                writer.WriteLine("namespace Geta.Epi.FontThumbnail\n{");

                writer.WriteLine("\t/// <summary>");
                writer.WriteLine($"\t/// Font Awesome. Version {latestVersionChange}.");
                writer.WriteLine("\t/// </summary>");

                writer.WriteLine($"\tpublic enum {enumName}");
                writer.WriteLine("\t{");

                foreach (var icon in icons)
                {
                    writer.WriteLine("\t\t/// <summary>");
                    writer.WriteLine($"\t\t/// {icon.Label.ToTitleCase()} ({icon.Name})");
                    WriteSearchTerms(writer, icon);
                    WriteChanges(writer, icon);
                    writer.WriteLine("\t\t/// </summary>");

                    var name = GetEnumSafeName(icon);
                    writer.WriteLine($"\t\t{name} = 0x{icon.Unicode},\n");
                }

                writer.WriteLine("\t}\n}");
            }
        }

        private static void WriteSearchTerms(StreamWriter writer, MetadataIcon icon)
        {
            if (icon.Search?.Terms?.Count > 0)
            {
                writer.WriteLine($"\t\t/// <para>Terms: {string.Join(", ", icon.Search.Terms)}</para>");
            }
        }

        private static void WriteChanges(StreamWriter writer, MetadataIcon icon)
        {
            var changes = icon.Changes.Select(x => x.FormatSemver()).OrderBy(x => x);

            writer.Write($"\t\t/// <para>Added in {changes.First()}");
            if (changes.Count() > 1)
            {
                var otherChanges = changes.Skip(1);
                var result = string.Join(", ", otherChanges.Take(otherChanges.Count() - 1)) + (otherChanges.Count() > 1 ? " and " : string.Empty) + otherChanges.LastOrDefault();
                writer.Write($", updated in {result}");
            }
            writer.Write(".</para>\n");
        }

        private static string GetEnumSafeName(MetadataIcon icon)
        {
            var name = icon.Name.Replace('-', ' ');
            name = name.ToTitleCase();
            name = name.Replace(" ", string.Empty);
            if (char.IsDigit(name[0]))
            {
                name = "_" + name;
            }

            return name;
        }
    }
}
