//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geta.Epi.FontThumbnail
{
    /// <summary>
    /// Font Awesome. Version 5.9.0.
    /// </summary>
    public enum FontAwesome5Brands
    {
        /// <summary>
        /// 500Px (500px)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        _500Px = 0xf26e,

        /// <summary>
        /// Accessible Icon (accessible-icon)
        /// <para>Terms: accessibility, handicap, person, wheelchair, wheelchair-alt</para>
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        AccessibleIcon = 0xf368,

        /// <summary>
        /// Accusoft (accusoft)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Accusoft = 0xf369,

        /// <summary>
        /// Acquisitions Incorporated (acquisitions-incorporated)
        /// <para>Terms: Dungeons &amp; Dragons, d&amp;d, dnd, fantasy, game, gaming, tabletop</para>
        /// <para>Added in 5.4.0, updated in 5.8.0.</para>
        /// </summary>
        AcquisitionsIncorporated = 0xf6af,

        /// <summary>
        /// App.Net (adn)
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        Adn = 0xf170,

        /// <summary>
        /// Adobe (adobe)
        /// <para>Terms: acrobat, app, design, illustrator, indesign, photoshop</para>
        /// <para>Added in 5.6.0, updated in 5.8.0.</para>
        /// </summary>
        Adobe = 0xf778,

        /// <summary>
        /// Adversal (adversal)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Adversal = 0xf36a,

        /// <summary>
        /// Affiliatetheme (affiliatetheme)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Affiliatetheme = 0xf36b,

        /// <summary>
        /// Airbnb (airbnb)
        /// <para>Added in 5.8.0.</para>
        /// </summary>
        Airbnb = 0xf834,

        /// <summary>
        /// Algolia (algolia)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Algolia = 0xf36c,

        /// <summary>
        /// Alipay (alipay)
        /// <para>Added in 5.3.0.</para>
        /// </summary>
        Alipay = 0xf642,

        /// <summary>
        /// Amazon (amazon)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        Amazon = 0xf270,

        /// <summary>
        /// Amazon Pay (amazon-pay)
        /// <para>Added in 5.0.2, updated in 5.8.0.</para>
        /// </summary>
        AmazonPay = 0xf42c,

        /// <summary>
        /// Amilia (amilia)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Amilia = 0xf36d,

        /// <summary>
        /// Android (android)
        /// <para>Terms: robot</para>
        /// <para>Added in 3.2.0, updated in 5.0.0 and 5.12.0.</para>
        /// </summary>
        Android = 0xf17b,

        /// <summary>
        /// Angellist (angellist)
        /// <para>Added in 4.2.0, updated in 5.0.0.</para>
        /// </summary>
        Angellist = 0xf209,

        /// <summary>
        /// Angry Creative (angrycreative)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Angrycreative = 0xf36e,

        /// <summary>
        /// Angular (angular)
        /// <para>Added in 5.0.0, updated in 5.8.0.</para>
        /// </summary>
        Angular = 0xf420,

        /// <summary>
        /// App Store (app-store)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        AppStore = 0xf36f,

        /// <summary>
        /// Ios App Store (app-store-ios)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        AppStoreIos = 0xf370,

        /// <summary>
        /// Apper Systems AB (apper)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Apper = 0xf371,

        /// <summary>
        /// Apple (apple)
        /// <para>Terms: fruit, ios, mac, operating system, os, osx</para>
        /// <para>Added in 3.2.0, updated in 5.0.0, 5.0.7 and 5.8.0.</para>
        /// </summary>
        Apple = 0xf179,

        /// <summary>
        /// Apple Pay (apple-pay)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        ApplePay = 0xf415,

        /// <summary>
        /// Artstation (artstation)
        /// <para>Added in 5.6.0, updated in 5.8.0.</para>
        /// </summary>
        Artstation = 0xf77a,

        /// <summary>
        /// Asymmetrik, Ltd. (asymmetrik)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Asymmetrik = 0xf372,

        /// <summary>
        /// Atlassian (atlassian)
        /// <para>Added in 5.6.0.</para>
        /// </summary>
        Atlassian = 0xf77b,

        /// <summary>
        /// Audible (audible)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Audible = 0xf373,

        /// <summary>
        /// Autoprefixer (autoprefixer)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Autoprefixer = 0xf41c,

        /// <summary>
        /// Avianex (avianex)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Avianex = 0xf374,

        /// <summary>
        /// Aviato (aviato)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Aviato = 0xf421,

        /// <summary>
        /// Amazon Web Services (AWS) (aws)
        /// <para>Added in 5.0.0, updated in 5.1.0.</para>
        /// </summary>
        Aws = 0xf375,

        /// <summary>
        /// Bandcamp (bandcamp)
        /// <para>Added in 4.7.0, updated in 5.0.0.</para>
        /// </summary>
        Bandcamp = 0xf2d5,

        /// <summary>
        /// Battle.Net (battle-net)
        /// <para>Added in 5.8.0.</para>
        /// </summary>
        BattleNet = 0xf835,

        /// <summary>
        /// Behance (behance)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Behance = 0xf1b4,

        /// <summary>
        /// Behance Square (behance-square)
        /// <para>Added in 4.1.0, updated in 5.0.0 and 5.0.3.</para>
        /// </summary>
        BehanceSquare = 0xf1b5,

        /// <summary>
        /// Bimobject (bimobject)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Bimobject = 0xf378,

        /// <summary>
        /// Bitbucket (bitbucket)
        /// <para>Terms: atlassian, bitbucket-square, git</para>
        /// <para>Added in 3.2.0, updated in 5.0.0, 5.6.0 and 5.8.0.</para>
        /// </summary>
        Bitbucket = 0xf171,

        /// <summary>
        /// Bitcoin (bitcoin)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Bitcoin = 0xf379,

        /// <summary>
        /// Bity (bity)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Bity = 0xf37a,

        /// <summary>
        /// Font Awesome Black Tie (black-tie)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        BlackTie = 0xf27e,

        /// <summary>
        /// Blackberry (blackberry)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Blackberry = 0xf37b,

        /// <summary>
        /// Blogger (blogger)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Blogger = 0xf37c,

        /// <summary>
        /// Blogger B (blogger-b)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        BloggerB = 0xf37d,

        /// <summary>
        /// Bluetooth (bluetooth)
        /// <para>Added in 4.5.0, updated in 5.0.0.</para>
        /// </summary>
        Bluetooth = 0xf293,

        /// <summary>
        /// Bluetooth (bluetooth-b)
        /// <para>Added in 4.5.0, updated in 5.0.0.</para>
        /// </summary>
        BluetoothB = 0xf294,

        /// <summary>
        /// Bootstrap (bootstrap)
        /// <para>Added in 5.8.0.</para>
        /// </summary>
        Bootstrap = 0xf836,

        /// <summary>
        /// BTC (btc)
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        Btc = 0xf15a,

        /// <summary>
        /// Buffer (buffer)
        /// <para>Added in 5.8.0.</para>
        /// </summary>
        Buffer = 0xf837,

        /// <summary>
        /// Büromöbel-Experte Gmbh &amp; Co. KG. (buromobelexperte)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Buromobelexperte = 0xf37f,

        /// <summary>
        /// Buy N Large (buy-n-large)
        /// <para>Added in 5.11.0.</para>
        /// </summary>
        BuyNLarge = 0xf8a6,

        /// <summary>
        /// Buysellads (buysellads)
        /// <para>Added in 4.3.0, updated in 5.0.0.</para>
        /// </summary>
        Buysellads = 0xf20d,

        /// <summary>
        /// Canadian Maple Leaf (canadian-maple-leaf)
        /// <para>Terms: canada, flag, flora, nature, plant</para>
        /// <para>Added in 5.6.0, updated in 5.8.0.</para>
        /// </summary>
        CanadianMapleLeaf = 0xf785,

        /// <summary>
        /// Amazon Pay Credit Card (cc-amazon-pay)
        /// <para>Added in 5.0.2.</para>
        /// </summary>
        CcAmazonPay = 0xf42d,

        /// <summary>
        /// American Express Credit Card (cc-amex)
        /// <para>Terms: amex</para>
        /// <para>Added in 4.2.0, updated in 5.0.0 and 5.7.0.</para>
        /// </summary>
        CcAmex = 0xf1f3,

        /// <summary>
        /// Apple Pay Credit Card (cc-apple-pay)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        CcApplePay = 0xf416,

        /// <summary>
        /// Diner&apos;s Club Credit Card (cc-diners-club)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        CcDinersClub = 0xf24c,

        /// <summary>
        /// Discover Credit Card (cc-discover)
        /// <para>Added in 4.2.0, updated in 5.0.0.</para>
        /// </summary>
        CcDiscover = 0xf1f2,

        /// <summary>
        /// JCB Credit Card (cc-jcb)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        CcJcb = 0xf24b,

        /// <summary>
        /// Mastercard Credit Card (cc-mastercard)
        /// <para>Added in 4.2.0, updated in 5.0.0.</para>
        /// </summary>
        CcMastercard = 0xf1f1,

        /// <summary>
        /// Paypal Credit Card (cc-paypal)
        /// <para>Added in 4.2.0, updated in 5.0.0.</para>
        /// </summary>
        CcPaypal = 0xf1f4,

        /// <summary>
        /// Stripe Credit Card (cc-stripe)
        /// <para>Added in 4.2.0, updated in 5.0.0.</para>
        /// </summary>
        CcStripe = 0xf1f5,

        /// <summary>
        /// Visa Credit Card (cc-visa)
        /// <para>Added in 4.2.0, updated in 5.0.0.</para>
        /// </summary>
        CcVisa = 0xf1f0,

        /// <summary>
        /// Centercode (centercode)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Centercode = 0xf380,

        /// <summary>
        /// Centos (centos)
        /// <para>Terms: linux, operating system, os</para>
        /// <para>Added in 5.6.0, updated in 5.8.0.</para>
        /// </summary>
        Centos = 0xf789,

        /// <summary>
        /// Chrome (chrome)
        /// <para>Terms: browser</para>
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        Chrome = 0xf268,

        /// <summary>
        /// Chromecast (chromecast)
        /// <para>Added in 5.8.0.</para>
        /// </summary>
        Chromecast = 0xf838,

        /// <summary>
        /// Cloudscale.Ch (cloudscale)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Cloudscale = 0xf383,

        /// <summary>
        /// Cloudsmith (cloudsmith)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Cloudsmith = 0xf384,

        /// <summary>
        /// Cloudversify (cloudversify)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Cloudversify = 0xf385,

        /// <summary>
        /// Codepen (codepen)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Codepen = 0xf1cb,

        /// <summary>
        /// Codie Pie (codiepie)
        /// <para>Added in 4.5.0, updated in 5.0.0.</para>
        /// </summary>
        Codiepie = 0xf284,

        /// <summary>
        /// Confluence (confluence)
        /// <para>Terms: atlassian</para>
        /// <para>Added in 5.6.0.</para>
        /// </summary>
        Confluence = 0xf78d,

        /// <summary>
        /// Connect Develop (connectdevelop)
        /// <para>Added in 4.3.0, updated in 5.0.0.</para>
        /// </summary>
        Connectdevelop = 0xf20e,

        /// <summary>
        /// Contao (contao)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        Contao = 0xf26d,

        /// <summary>
        /// Cotton Bureau (cotton-bureau)
        /// <para>Terms: clothing, t-shirts, tshirts</para>
        /// <para>Added in 5.10.0.</para>
        /// </summary>
        CottonBureau = 0xf89e,

        /// <summary>
        /// Cpanel (cpanel)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Cpanel = 0xf388,

        /// <summary>
        /// Creative Commons (creative-commons)
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.0.11 and 5.1.0.</para>
        /// </summary>
        CreativeCommons = 0xf25e,

        /// <summary>
        /// Creative Commons Attribution (creative-commons-by)
        /// <para>Added in 5.0.11.</para>
        /// </summary>
        CreativeCommonsBy = 0xf4e7,

        /// <summary>
        /// Creative Commons Noncommercial (creative-commons-nc)
        /// <para>Added in 5.0.11.</para>
        /// </summary>
        CreativeCommonsNc = 0xf4e8,

        /// <summary>
        /// Creative Commons Noncommercial (Euro Sign) (creative-commons-nc-eu)
        /// <para>Added in 5.0.11.</para>
        /// </summary>
        CreativeCommonsNcEu = 0xf4e9,

        /// <summary>
        /// Creative Commons Noncommercial (Yen Sign) (creative-commons-nc-jp)
        /// <para>Added in 5.0.11.</para>
        /// </summary>
        CreativeCommonsNcJp = 0xf4ea,

        /// <summary>
        /// Creative Commons No Derivative Works (creative-commons-nd)
        /// <para>Added in 5.0.11.</para>
        /// </summary>
        CreativeCommonsNd = 0xf4eb,

        /// <summary>
        /// Creative Commons Public Domain (creative-commons-pd)
        /// <para>Added in 5.0.11.</para>
        /// </summary>
        CreativeCommonsPd = 0xf4ec,

        /// <summary>
        /// Alternate Creative Commons Public Domain (creative-commons-pd-alt)
        /// <para>Added in 5.0.11.</para>
        /// </summary>
        CreativeCommonsPdAlt = 0xf4ed,

        /// <summary>
        /// Creative Commons Remix (creative-commons-remix)
        /// <para>Added in 5.0.11.</para>
        /// </summary>
        CreativeCommonsRemix = 0xf4ee,

        /// <summary>
        /// Creative Commons Share Alike (creative-commons-sa)
        /// <para>Added in 5.0.11.</para>
        /// </summary>
        CreativeCommonsSa = 0xf4ef,

        /// <summary>
        /// Creative Commons Sampling (creative-commons-sampling)
        /// <para>Added in 5.0.11.</para>
        /// </summary>
        CreativeCommonsSampling = 0xf4f0,

        /// <summary>
        /// Creative Commons Sampling + (creative-commons-sampling-plus)
        /// <para>Added in 5.0.11.</para>
        /// </summary>
        CreativeCommonsSamplingPlus = 0xf4f1,

        /// <summary>
        /// Creative Commons Share (creative-commons-share)
        /// <para>Added in 5.0.11.</para>
        /// </summary>
        CreativeCommonsShare = 0xf4f2,

        /// <summary>
        /// Creative Commons CC0 (creative-commons-zero)
        /// <para>Added in 5.0.11, updated in 5.4.0.</para>
        /// </summary>
        CreativeCommonsZero = 0xf4f3,

        /// <summary>
        /// Critical Role (critical-role)
        /// <para>Terms: Dungeons &amp; Dragons, d&amp;d, dnd, fantasy, game, gaming, tabletop</para>
        /// <para>Added in 5.4.0, updated in 5.8.0.</para>
        /// </summary>
        CriticalRole = 0xf6c9,

        /// <summary>
        /// CSS 3 Logo (css3)
        /// <para>Terms: code</para>
        /// <para>Added in 3.1.0, updated in 5.0.0.</para>
        /// </summary>
        Css3 = 0xf13c,

        /// <summary>
        /// Alternate CSS3 Logo (css3-alt)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Css3Alt = 0xf38b,

        /// <summary>
        /// Cuttlefish (cuttlefish)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Cuttlefish = 0xf38c,

        /// <summary>
        /// Dungeons &amp; Dragons (d-and-d)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        DAndD = 0xf38d,

        /// <summary>
        /// D&amp;D Beyond (d-and-d-beyond)
        /// <para>Terms: Dungeons &amp; Dragons, d&amp;d, dnd, fantasy, gaming, tabletop</para>
        /// <para>Added in 5.4.0.</para>
        /// </summary>
        DAndDBeyond = 0xf6ca,

        /// <summary>
        /// Dailymotion (dailymotion)
        /// <para>Added in 5.12.1.</para>
        /// </summary>
        Dailymotion = 0xf952,

        /// <summary>
        /// Dashcube (dashcube)
        /// <para>Added in 4.3.0, updated in 5.0.0 and 5.0.3.</para>
        /// </summary>
        Dashcube = 0xf210,

        /// <summary>
        /// Delicious (delicious)
        /// <para>Added in 4.1.0, updated in 5.0.0 and 5.7.0.</para>
        /// </summary>
        Delicious = 0xf1a5,

        /// <summary>
        /// Deploy.Dog (deploydog)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Deploydog = 0xf38e,

        /// <summary>
        /// Deskpro (deskpro)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Deskpro = 0xf38f,

        /// <summary>
        /// DEV (dev)
        /// <para>Added in 5.4.0.</para>
        /// </summary>
        Dev = 0xf6cc,

        /// <summary>
        /// Deviantart (deviantart)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Deviantart = 0xf1bd,

        /// <summary>
        /// DHL (dhl)
        /// <para>Terms: Dalsey, Hillblom and Lynn, german, package, shipping</para>
        /// <para>Added in 5.6.0.</para>
        /// </summary>
        Dhl = 0xf790,

        /// <summary>
        /// Diaspora (diaspora)
        /// <para>Added in 5.6.0, updated in 5.8.0.</para>
        /// </summary>
        Diaspora = 0xf791,

        /// <summary>
        /// Digg Logo (digg)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Digg = 0xf1a6,

        /// <summary>
        /// Digital Ocean (digital-ocean)
        /// <para>Added in 5.0.0, updated in 5.7.0.</para>
        /// </summary>
        DigitalOcean = 0xf391,

        /// <summary>
        /// Discord (discord)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Discord = 0xf392,

        /// <summary>
        /// Discourse (discourse)
        /// <para>Added in 5.0.0, updated in 5.0.3.</para>
        /// </summary>
        Discourse = 0xf393,

        /// <summary>
        /// Dochub (dochub)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Dochub = 0xf394,

        /// <summary>
        /// Docker (docker)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Docker = 0xf395,

        /// <summary>
        /// Draft2digital (draft2digital)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Draft2digital = 0xf396,

        /// <summary>
        /// Dribbble (dribbble)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Dribbble = 0xf17d,

        /// <summary>
        /// Dribbble Square (dribbble-square)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        DribbbleSquare = 0xf397,

        /// <summary>
        /// Dropbox (dropbox)
        /// <para>Added in 3.2.0, updated in 5.0.0 and 5.0.1.</para>
        /// </summary>
        Dropbox = 0xf16b,

        /// <summary>
        /// Drupal Logo (drupal)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Drupal = 0xf1a9,

        /// <summary>
        /// Dyalog (dyalog)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Dyalog = 0xf399,

        /// <summary>
        /// Earlybirds (earlybirds)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Earlybirds = 0xf39a,

        /// <summary>
        /// Ebay (ebay)
        /// <para>Added in 5.0.11, updated in 5.7.0.</para>
        /// </summary>
        Ebay = 0xf4f4,

        /// <summary>
        /// Edge Browser (edge)
        /// <para>Terms: browser, ie</para>
        /// <para>Added in 4.5.0, updated in 5.0.0 and 5.12.1.</para>
        /// </summary>
        Edge = 0xf282,

        /// <summary>
        /// Elementor (elementor)
        /// <para>Added in 5.0.3.</para>
        /// </summary>
        Elementor = 0xf430,

        /// <summary>
        /// Ello (ello)
        /// <para>Added in 5.2.0.</para>
        /// </summary>
        Ello = 0xf5f1,

        /// <summary>
        /// Ember (ember)
        /// <para>Added in 5.0.0, updated in 5.0.3.</para>
        /// </summary>
        Ember = 0xf423,

        /// <summary>
        /// Galactic Empire (empire)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Empire = 0xf1d1,

        /// <summary>
        /// Envira Gallery (envira)
        /// <para>Terms: leaf</para>
        /// <para>Added in 4.6.0, updated in 5.0.0.</para>
        /// </summary>
        Envira = 0xf299,

        /// <summary>
        /// Erlang (erlang)
        /// <para>Added in 5.0.0, updated in 5.0.3 and 5.7.0.</para>
        /// </summary>
        Erlang = 0xf39d,

        /// <summary>
        /// Ethereum (ethereum)
        /// <para>Added in 5.0.2.</para>
        /// </summary>
        Ethereum = 0xf42e,

        /// <summary>
        /// Etsy (etsy)
        /// <para>Added in 4.7.0, updated in 5.0.0.</para>
        /// </summary>
        Etsy = 0xf2d7,

        /// <summary>
        /// Evernote (evernote)
        /// <para>Added in 5.8.0.</para>
        /// </summary>
        Evernote = 0xf839,

        /// <summary>
        /// Expeditedssl (expeditedssl)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        Expeditedssl = 0xf23e,

        /// <summary>
        /// Facebook (facebook)
        /// <para>Terms: facebook-official, social network</para>
        /// <para>Added in 2.0.0, updated in 5.0.0 and 5.8.2.</para>
        /// </summary>
        Facebook = 0xf09a,

        /// <summary>
        /// Facebook F (facebook-f)
        /// <para>Terms: facebook</para>
        /// <para>Added in 5.0.0, updated in 5.8.2.</para>
        /// </summary>
        FacebookF = 0xf39e,

        /// <summary>
        /// Facebook Messenger (facebook-messenger)
        /// <para>Added in 5.0.0, updated in 5.8.2 and 5.9.0.</para>
        /// </summary>
        FacebookMessenger = 0xf39f,

        /// <summary>
        /// Facebook Square (facebook-square)
        /// <para>Terms: social network</para>
        /// <para>Added in 1.0.0, updated in 5.0.0 and 5.8.2.</para>
        /// </summary>
        FacebookSquare = 0xf082,

        /// <summary>
        /// Fantasy Flight-Games (fantasy-flight-games)
        /// <para>Terms: Dungeons &amp; Dragons, d&amp;d, dnd, fantasy, game, gaming, tabletop</para>
        /// <para>Added in 5.4.0.</para>
        /// </summary>
        FantasyFlightGames = 0xf6dc,

        /// <summary>
        /// Fedex (fedex)
        /// <para>Terms: Federal Express, package, shipping</para>
        /// <para>Added in 5.6.0.</para>
        /// </summary>
        Fedex = 0xf797,

        /// <summary>
        /// Fedora (fedora)
        /// <para>Terms: linux, operating system, os</para>
        /// <para>Added in 5.6.0, updated in 5.6.3 and 5.8.0.</para>
        /// </summary>
        Fedora = 0xf798,

        /// <summary>
        /// Figma (figma)
        /// <para>Terms: app, design, interface</para>
        /// <para>Added in 5.6.0, updated in 5.7.0 and 5.8.0.</para>
        /// </summary>
        Figma = 0xf799,

        /// <summary>
        /// Firefox (firefox)
        /// <para>Terms: browser</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.0.1 and 5.12.0.</para>
        /// </summary>
        Firefox = 0xf269,

        /// <summary>
        /// Firefox Browser (firefox-browser)
        /// <para>Terms: browser</para>
        /// <para>Added in 5.12.0.</para>
        /// </summary>
        FirefoxBrowser = 0xf907,

        /// <summary>
        /// First Order (first-order)
        /// <para>Added in 4.6.0, updated in 5.0.0.</para>
        /// </summary>
        FirstOrder = 0xf2b0,

        /// <summary>
        /// Alternate First Order (first-order-alt)
        /// <para>Added in 5.0.12.</para>
        /// </summary>
        FirstOrderAlt = 0xf50a,

        /// <summary>
        /// Firstdraft (firstdraft)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Firstdraft = 0xf3a1,

        /// <summary>
        /// Flickr (flickr)
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        Flickr = 0xf16e,

        /// <summary>
        /// Flipboard (flipboard)
        /// <para>Added in 5.0.5, updated in 5.0.9.</para>
        /// </summary>
        Flipboard = 0xf44d,

        /// <summary>
        /// Fly (fly)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Fly = 0xf417,

        /// <summary>
        /// Font Awesome (font-awesome)
        /// <para>Terms: meanpath</para>
        /// <para>Added in 4.6.0, updated in 5.0.0.</para>
        /// </summary>
        FontAwesome = 0xf2b4,

        /// <summary>
        /// Alternate Font Awesome (font-awesome-alt)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        FontAwesomeAlt = 0xf35c,

        /// <summary>
        /// Font Awesome Flag (font-awesome-flag)
        /// <para>Added in 5.0.0, updated in 5.0.1.</para>
        /// </summary>
        FontAwesomeFlag = 0xf425,

        /// <summary>
        /// Fonticons (fonticons)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        Fonticons = 0xf280,

        /// <summary>
        /// Fonticons Fi (fonticons-fi)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        FonticonsFi = 0xf3a2,

        /// <summary>
        /// Fort Awesome (fort-awesome)
        /// <para>Terms: castle</para>
        /// <para>Added in 4.5.0, updated in 5.0.0 and 5.0.3.</para>
        /// </summary>
        FortAwesome = 0xf286,

        /// <summary>
        /// Alternate Fort Awesome (fort-awesome-alt)
        /// <para>Terms: castle</para>
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        FortAwesomeAlt = 0xf3a3,

        /// <summary>
        /// Forumbee (forumbee)
        /// <para>Added in 4.3.0, updated in 5.0.0.</para>
        /// </summary>
        Forumbee = 0xf211,

        /// <summary>
        /// Foursquare (foursquare)
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        Foursquare = 0xf180,

        /// <summary>
        /// Freecodecamp (free-code-camp)
        /// <para>Added in 4.7.0, updated in 5.0.0 and 5.12.0.</para>
        /// </summary>
        FreeCodeCamp = 0xf2c5,

        /// <summary>
        /// Freebsd (freebsd)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Freebsd = 0xf3a4,

        /// <summary>
        /// Fulcrum (fulcrum)
        /// <para>Added in 5.0.12, updated in 5.8.0.</para>
        /// </summary>
        Fulcrum = 0xf50b,

        /// <summary>
        /// Galactic Republic (galactic-republic)
        /// <para>Terms: politics, star wars</para>
        /// <para>Added in 5.0.12.</para>
        /// </summary>
        GalacticRepublic = 0xf50c,

        /// <summary>
        /// Galactic Senate (galactic-senate)
        /// <para>Terms: star wars</para>
        /// <para>Added in 5.0.12.</para>
        /// </summary>
        GalacticSenate = 0xf50d,

        /// <summary>
        /// Get Pocket (get-pocket)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        GetPocket = 0xf265,

        /// <summary>
        /// GG Currency (gg)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        Gg = 0xf260,

        /// <summary>
        /// GG Currency Circle (gg-circle)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        GgCircle = 0xf261,

        /// <summary>
        /// Git (git)
        /// <para>Added in 4.1.0, updated in 5.0.0 and 5.8.2.</para>
        /// </summary>
        Git = 0xf1d3,

        /// <summary>
        /// Git Alt (git-alt)
        /// <para>Added in 5.8.2.</para>
        /// </summary>
        GitAlt = 0xf841,

        /// <summary>
        /// Git Square (git-square)
        /// <para>Added in 4.1.0, updated in 5.0.0 and 5.8.2.</para>
        /// </summary>
        GitSquare = 0xf1d2,

        /// <summary>
        /// Github (github)
        /// <para>Terms: octocat</para>
        /// <para>Added in 2.0.0, updated in 5.0.0.</para>
        /// </summary>
        Github = 0xf09b,

        /// <summary>
        /// Alternate Github (github-alt)
        /// <para>Terms: octocat</para>
        /// <para>Added in 3.0.0, updated in 5.0.0.</para>
        /// </summary>
        GithubAlt = 0xf113,

        /// <summary>
        /// Github Square (github-square)
        /// <para>Terms: octocat</para>
        /// <para>Added in 1.0.0, updated in 5.0.0.</para>
        /// </summary>
        GithubSquare = 0xf092,

        /// <summary>
        /// Gitkraken (gitkraken)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Gitkraken = 0xf3a6,

        /// <summary>
        /// Gitlab (gitlab)
        /// <para>Terms: Axosoft</para>
        /// <para>Added in 4.6.0, updated in 5.0.0 and 5.7.0.</para>
        /// </summary>
        Gitlab = 0xf296,

        /// <summary>
        /// Gitter (gitter)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Gitter = 0xf426,

        /// <summary>
        /// Glide (glide)
        /// <para>Added in 4.6.0, updated in 5.0.0.</para>
        /// </summary>
        Glide = 0xf2a5,

        /// <summary>
        /// Glide G (glide-g)
        /// <para>Added in 4.6.0, updated in 5.0.0.</para>
        /// </summary>
        GlideG = 0xf2a6,

        /// <summary>
        /// Gofore (gofore)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Gofore = 0xf3a7,

        /// <summary>
        /// Goodreads (goodreads)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Goodreads = 0xf3a8,

        /// <summary>
        /// Goodreads G (goodreads-g)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        GoodreadsG = 0xf3a9,

        /// <summary>
        /// Google Logo (google)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Google = 0xf1a0,

        /// <summary>
        /// Google Drive (google-drive)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        GoogleDrive = 0xf3aa,

        /// <summary>
        /// Google Play (google-play)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        GooglePlay = 0xf3ab,

        /// <summary>
        /// Google Plus (google-plus)
        /// <para>Terms: google-plus-circle, google-plus-official</para>
        /// <para>Added in 4.6.0, updated in 5.0.0.</para>
        /// </summary>
        GooglePlus = 0xf2b3,

        /// <summary>
        /// Google Plus G (google-plus-g)
        /// <para>Terms: google-plus, social network</para>
        /// <para>Added in 2.0.0, updated in 5.0.0.</para>
        /// </summary>
        GooglePlusG = 0xf0d5,

        /// <summary>
        /// Google Plus Square (google-plus-square)
        /// <para>Terms: social network</para>
        /// <para>Added in 2.0.0, updated in 5.0.0.</para>
        /// </summary>
        GooglePlusSquare = 0xf0d4,

        /// <summary>
        /// Google Wallet (google-wallet)
        /// <para>Added in 4.2.0, updated in 5.0.0.</para>
        /// </summary>
        GoogleWallet = 0xf1ee,

        /// <summary>
        /// Gratipay (Gittip) (gratipay)
        /// <para>Terms: favorite, heart, like, love</para>
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        Gratipay = 0xf184,

        /// <summary>
        /// Grav (grav)
        /// <para>Added in 4.7.0, updated in 5.0.0.</para>
        /// </summary>
        Grav = 0xf2d6,

        /// <summary>
        /// Gripfire, Inc. (gripfire)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Gripfire = 0xf3ac,

        /// <summary>
        /// Grunt (grunt)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Grunt = 0xf3ad,

        /// <summary>
        /// Gulp (gulp)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Gulp = 0xf3ae,

        /// <summary>
        /// Hacker News (hacker-news)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        HackerNews = 0xf1d4,

        /// <summary>
        /// Hacker News Square (hacker-news-square)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        HackerNewsSquare = 0xf3af,

        /// <summary>
        /// Hackerrank (hackerrank)
        /// <para>Added in 5.2.0, updated in 5.8.0.</para>
        /// </summary>
        Hackerrank = 0xf5f7,

        /// <summary>
        /// Hips (hips)
        /// <para>Added in 5.0.5.</para>
        /// </summary>
        Hips = 0xf452,

        /// <summary>
        /// Hireahelper (hire-a-helper)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        HireAHelper = 0xf3b0,

        /// <summary>
        /// Hooli (hooli)
        /// <para>Added in 5.0.0, updated in 5.7.0.</para>
        /// </summary>
        Hooli = 0xf427,

        /// <summary>
        /// Hornbill (hornbill)
        /// <para>Added in 5.1.0, updated in 5.8.0.</para>
        /// </summary>
        Hornbill = 0xf592,

        /// <summary>
        /// Hotjar (hotjar)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Hotjar = 0xf3b1,

        /// <summary>
        /// Houzz (houzz)
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.0.9 and 5.8.0.</para>
        /// </summary>
        Houzz = 0xf27c,

        /// <summary>
        /// HTML 5 Logo (html5)
        /// <para>Added in 3.1.0, updated in 5.0.0.</para>
        /// </summary>
        Html5 = 0xf13b,

        /// <summary>
        /// Hubspot (hubspot)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Hubspot = 0xf3b2,

        /// <summary>
        /// Ideal (ideal)
        /// <para>Added in 5.12.0.</para>
        /// </summary>
        Ideal = 0xf913,

        /// <summary>
        /// IMDB (imdb)
        /// <para>Added in 4.7.0, updated in 5.0.0.</para>
        /// </summary>
        Imdb = 0xf2d8,

        /// <summary>
        /// Instagram (instagram)
        /// <para>Added in 4.6.0, updated in 5.0.0.</para>
        /// </summary>
        Instagram = 0xf16d,

        /// <summary>
        /// Instagram Square (instagram-square)
        /// <para>Added in 5.12.1.</para>
        /// </summary>
        InstagramSquare = 0xf955,

        /// <summary>
        /// Intercom (intercom)
        /// <para>Terms: app, customer, messenger</para>
        /// <para>Added in 5.6.0.</para>
        /// </summary>
        Intercom = 0xf7af,

        /// <summary>
        /// Internet-Explorer (internet-explorer)
        /// <para>Terms: browser, ie</para>
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        InternetExplorer = 0xf26b,

        /// <summary>
        /// Invision (invision)
        /// <para>Terms: app, design, interface</para>
        /// <para>Added in 5.6.0.</para>
        /// </summary>
        Invision = 0xf7b0,

        /// <summary>
        /// Ioxhost (ioxhost)
        /// <para>Added in 4.2.0, updated in 5.0.0.</para>
        /// </summary>
        Ioxhost = 0xf208,

        /// <summary>
        /// Itch.Io (itch-io)
        /// <para>Added in 5.8.0.</para>
        /// </summary>
        ItchIo = 0xf83a,

        /// <summary>
        /// Itunes (itunes)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Itunes = 0xf3b4,

        /// <summary>
        /// Itunes Note (itunes-note)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        ItunesNote = 0xf3b5,

        /// <summary>
        /// Java (java)
        /// <para>Added in 5.0.10, updated in 5.7.0 and 5.8.0.</para>
        /// </summary>
        Java = 0xf4e4,

        /// <summary>
        /// Jedi Order (jedi-order)
        /// <para>Terms: star wars</para>
        /// <para>Added in 5.0.12, updated in 5.7.0.</para>
        /// </summary>
        JediOrder = 0xf50e,

        /// <summary>
        /// Jenkis (jenkins)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Jenkins = 0xf3b6,

        /// <summary>
        /// Jira (jira)
        /// <para>Terms: atlassian</para>
        /// <para>Added in 5.6.0.</para>
        /// </summary>
        Jira = 0xf7b1,

        /// <summary>
        /// Joget (joget)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Joget = 0xf3b7,

        /// <summary>
        /// Joomla Logo (joomla)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Joomla = 0xf1aa,

        /// <summary>
        /// Javascript (JS) (js)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Js = 0xf3b8,

        /// <summary>
        /// Javascript (JS) Square (js-square)
        /// <para>Added in 5.0.0, updated in 5.0.3.</para>
        /// </summary>
        JsSquare = 0xf3b9,

        /// <summary>
        /// Jsfiddle (jsfiddle)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Jsfiddle = 0xf1cc,

        /// <summary>
        /// Kaggle (kaggle)
        /// <para>Added in 5.2.0, updated in 5.8.0.</para>
        /// </summary>
        Kaggle = 0xf5fa,

        /// <summary>
        /// Keybase (keybase)
        /// <para>Added in 5.0.11, updated in 5.10.2, 5.11.0 and 5.8.0.</para>
        /// </summary>
        Keybase = 0xf4f5,

        /// <summary>
        /// Keycdn (keycdn)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Keycdn = 0xf3ba,

        /// <summary>
        /// Kickstarter (kickstarter)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Kickstarter = 0xf3bb,

        /// <summary>
        /// Kickstarter K (kickstarter-k)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        KickstarterK = 0xf3bc,

        /// <summary>
        /// KORVUE (korvue)
        /// <para>Added in 5.0.2.</para>
        /// </summary>
        Korvue = 0xf42f,

        /// <summary>
        /// Laravel (laravel)
        /// <para>Added in 5.0.0, updated in 5.0.3 and 5.11.2.</para>
        /// </summary>
        Laravel = 0xf3bd,

        /// <summary>
        /// Last.Fm (lastfm)
        /// <para>Added in 4.2.0, updated in 5.0.0.</para>
        /// </summary>
        Lastfm = 0xf202,

        /// <summary>
        /// Last.Fm Square (lastfm-square)
        /// <para>Added in 4.2.0, updated in 5.0.0 and 5.0.11.</para>
        /// </summary>
        LastfmSquare = 0xf203,

        /// <summary>
        /// Leanpub (leanpub)
        /// <para>Added in 4.3.0, updated in 5.0.0.</para>
        /// </summary>
        Leanpub = 0xf212,

        /// <summary>
        /// Less (less)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Less = 0xf41d,

        /// <summary>
        /// Line (line)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Line = 0xf3c0,

        /// <summary>
        /// Linkedin (linkedin)
        /// <para>Terms: linkedin-square</para>
        /// <para>Added in 1.0.0, updated in 5.0.0.</para>
        /// </summary>
        Linkedin = 0xf08c,

        /// <summary>
        /// Linkedin In (linkedin-in)
        /// <para>Terms: linkedin</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 5.4.1, 5.8.0 and 5.8.1.</para>
        /// </summary>
        LinkedinIn = 0xf0e1,

        /// <summary>
        /// Linode (linode)
        /// <para>Added in 4.7.0, updated in 5.0.0.</para>
        /// </summary>
        Linode = 0xf2b8,

        /// <summary>
        /// Linux (linux)
        /// <para>Terms: tux</para>
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        Linux = 0xf17c,

        /// <summary>
        /// Lyft (lyft)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Lyft = 0xf3c3,

        /// <summary>
        /// Magento (magento)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Magento = 0xf3c4,

        /// <summary>
        /// Mailchimp (mailchimp)
        /// <para>Added in 5.1.0, updated in 5.7.0, 5.8.0 and 5.8.2.</para>
        /// </summary>
        Mailchimp = 0xf59e,

        /// <summary>
        /// Mandalorian (mandalorian)
        /// <para>Added in 5.0.12, updated in 5.8.0.</para>
        /// </summary>
        Mandalorian = 0xf50f,

        /// <summary>
        /// Markdown (markdown)
        /// <para>Added in 5.2.0, updated in 5.7.0.</para>
        /// </summary>
        Markdown = 0xf60f,

        /// <summary>
        /// Mastodon (mastodon)
        /// <para>Added in 5.0.11, updated in 5.8.0.</para>
        /// </summary>
        Mastodon = 0xf4f6,

        /// <summary>
        /// Maxcdn (maxcdn)
        /// <para>Added in 3.1.0, updated in 5.0.0.</para>
        /// </summary>
        Maxcdn = 0xf136,

        /// <summary>
        /// Material Design For Bootstrap (mdb)
        /// <para>Added in 5.11.0.</para>
        /// </summary>
        Mdb = 0xf8ca,

        /// <summary>
        /// Medapps (medapps)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Medapps = 0xf3c6,

        /// <summary>
        /// Medium (medium)
        /// <para>Added in 4.3.0, updated in 5.0.0.</para>
        /// </summary>
        Medium = 0xf23a,

        /// <summary>
        /// Medium M (medium-m)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        MediumM = 0xf3c7,

        /// <summary>
        /// MRT (medrt)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Medrt = 0xf3c8,

        /// <summary>
        /// Meetup (meetup)
        /// <para>Added in 4.7.0, updated in 5.0.0.</para>
        /// </summary>
        Meetup = 0xf2e0,

        /// <summary>
        /// Megaport (megaport)
        /// <para>Added in 5.1.0.</para>
        /// </summary>
        Megaport = 0xf5a3,

        /// <summary>
        /// Mendeley (mendeley)
        /// <para>Added in 5.6.0.</para>
        /// </summary>
        Mendeley = 0xf7b3,

        /// <summary>
        /// Micro.Blog (microblog)
        /// <para>Added in 5.12.0.</para>
        /// </summary>
        Microblog = 0xf91a,

        /// <summary>
        /// Microsoft (microsoft)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Microsoft = 0xf3ca,

        /// <summary>
        /// Mix (mix)
        /// <para>Added in 5.0.0, updated in 5.0.3.</para>
        /// </summary>
        Mix = 0xf3cb,

        /// <summary>
        /// Mixcloud (mixcloud)
        /// <para>Added in 4.5.0, updated in 5.0.0.</para>
        /// </summary>
        Mixcloud = 0xf289,

        /// <summary>
        /// Mixer (mixer)
        /// <para>Added in 5.12.1.</para>
        /// </summary>
        Mixer = 0xf956,

        /// <summary>
        /// Mizuni (mizuni)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Mizuni = 0xf3cc,

        /// <summary>
        /// MODX (modx)
        /// <para>Added in 4.5.0, updated in 5.0.0.</para>
        /// </summary>
        Modx = 0xf285,

        /// <summary>
        /// Monero (monero)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Monero = 0xf3d0,

        /// <summary>
        /// Napster (napster)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Napster = 0xf3d2,

        /// <summary>
        /// Neos (neos)
        /// <para>Added in 5.2.0, updated in 5.8.0.</para>
        /// </summary>
        Neos = 0xf612,

        /// <summary>
        /// Nimblr (nimblr)
        /// <para>Added in 5.1.0, updated in 5.8.0.</para>
        /// </summary>
        Nimblr = 0xf5a8,

        /// <summary>
        /// Node.Js (node)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Node = 0xf419,

        /// <summary>
        /// Node.Js JS (node-js)
        /// <para>Added in 5.0.0, updated in 5.0.3.</para>
        /// </summary>
        NodeJs = 0xf3d3,

        /// <summary>
        /// Npm (npm)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Npm = 0xf3d4,

        /// <summary>
        /// NS8 (ns8)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Ns8 = 0xf3d5,

        /// <summary>
        /// Nutritionix (nutritionix)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Nutritionix = 0xf3d6,

        /// <summary>
        /// Odnoklassniki (odnoklassniki)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        Odnoklassniki = 0xf263,

        /// <summary>
        /// Odnoklassniki Square (odnoklassniki-square)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        OdnoklassnikiSquare = 0xf264,

        /// <summary>
        /// Old Republic (old-republic)
        /// <para>Terms: politics, star wars</para>
        /// <para>Added in 5.0.12.</para>
        /// </summary>
        OldRepublic = 0xf510,

        /// <summary>
        /// Opencart (opencart)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        Opencart = 0xf23d,

        /// <summary>
        /// Openid (openid)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Openid = 0xf19b,

        /// <summary>
        /// Opera (opera)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        Opera = 0xf26a,

        /// <summary>
        /// Optin Monster (optin-monster)
        /// <para>Added in 4.4.0, updated in 5.0.0 and 5.7.0.</para>
        /// </summary>
        OptinMonster = 0xf23c,

        /// <summary>
        /// ORCID (orcid)
        /// <para>Added in 5.11.0.</para>
        /// </summary>
        Orcid = 0xf8d2,

        /// <summary>
        /// Open Source Initiative (osi)
        /// <para>Added in 5.0.0, updated in 5.8.0.</para>
        /// </summary>
        Osi = 0xf41a,

        /// <summary>
        /// Page4 Corporation (page4)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Page4 = 0xf3d7,

        /// <summary>
        /// Pagelines (pagelines)
        /// <para>Terms: eco, flora, leaf, leaves, nature, plant, tree</para>
        /// <para>Added in 4.0.0, updated in 5.0.0.</para>
        /// </summary>
        Pagelines = 0xf18c,

        /// <summary>
        /// Palfed (palfed)
        /// <para>Added in 5.0.0, updated in 5.0.3.</para>
        /// </summary>
        Palfed = 0xf3d8,

        /// <summary>
        /// Patreon (patreon)
        /// <para>Added in 5.0.0, updated in 5.0.3.</para>
        /// </summary>
        Patreon = 0xf3d9,

        /// <summary>
        /// Paypal (paypal)
        /// <para>Added in 4.2.0, updated in 5.0.0.</para>
        /// </summary>
        Paypal = 0xf1ed,

        /// <summary>
        /// Penny Arcade (penny-arcade)
        /// <para>Terms: Dungeons &amp; Dragons, d&amp;d, dnd, fantasy, game, gaming, pax, tabletop</para>
        /// <para>Added in 5.4.0.</para>
        /// </summary>
        PennyArcade = 0xf704,

        /// <summary>
        /// Periscope (periscope)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Periscope = 0xf3da,

        /// <summary>
        /// Phabricator (phabricator)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Phabricator = 0xf3db,

        /// <summary>
        /// Phoenix Framework (phoenix-framework)
        /// <para>Added in 5.0.0, updated in 5.0.3.</para>
        /// </summary>
        PhoenixFramework = 0xf3dc,

        /// <summary>
        /// Phoenix Squadron (phoenix-squadron)
        /// <para>Added in 5.0.12, updated in 5.8.0.</para>
        /// </summary>
        PhoenixSquadron = 0xf511,

        /// <summary>
        /// PHP (php)
        /// <para>Added in 5.0.5.</para>
        /// </summary>
        Php = 0xf457,

        /// <summary>
        /// Pied Piper Logo (pied-piper)
        /// <para>Added in 4.6.0, updated in 5.0.0, 5.0.10 and 5.12.0.</para>
        /// </summary>
        PiedPiper = 0xf2ae,

        /// <summary>
        /// Alternate Pied Piper Logo (Old) (pied-piper-alt)
        /// <para>Added in 4.1.0, updated in 5.0.0 and 5.7.0.</para>
        /// </summary>
        PiedPiperAlt = 0xf1a8,

        /// <summary>
        /// Pied Piper Hat (Old) (pied-piper-hat)
        /// <para>Terms: clothing</para>
        /// <para>Added in 5.0.10.</para>
        /// </summary>
        PiedPiperHat = 0xf4e5,

        /// <summary>
        /// Pied Piper PP Logo (Old) (pied-piper-pp)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        PiedPiperPp = 0xf1a7,

        /// <summary>
        /// Pied Piper Square Logo (Old) (pied-piper-square)
        /// <para>Added in 5.12.0.</para>
        /// </summary>
        PiedPiperSquare = 0xf91e,

        /// <summary>
        /// Pinterest (pinterest)
        /// <para>Added in 2.0.0, updated in 5.0.0.</para>
        /// </summary>
        Pinterest = 0xf0d2,

        /// <summary>
        /// Pinterest P (pinterest-p)
        /// <para>Added in 4.3.0, updated in 5.0.0.</para>
        /// </summary>
        PinterestP = 0xf231,

        /// <summary>
        /// Pinterest Square (pinterest-square)
        /// <para>Added in 2.0.0, updated in 5.0.0.</para>
        /// </summary>
        PinterestSquare = 0xf0d3,

        /// <summary>
        /// Playstation (playstation)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Playstation = 0xf3df,

        /// <summary>
        /// Product Hunt (product-hunt)
        /// <para>Added in 4.5.0, updated in 5.0.0.</para>
        /// </summary>
        ProductHunt = 0xf288,

        /// <summary>
        /// Pushed (pushed)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Pushed = 0xf3e1,

        /// <summary>
        /// Python (python)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Python = 0xf3e2,

        /// <summary>
        /// QQ (qq)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Qq = 0xf1d6,

        /// <summary>
        /// Quinscape (quinscape)
        /// <para>Added in 5.0.5, updated in 5.7.0 and 5.8.0.</para>
        /// </summary>
        Quinscape = 0xf459,

        /// <summary>
        /// Quora (quora)
        /// <para>Added in 4.7.0, updated in 5.0.0.</para>
        /// </summary>
        Quora = 0xf2c4,

        /// <summary>
        /// R Project (r-project)
        /// <para>Added in 5.0.11, updated in 5.0.12.</para>
        /// </summary>
        RProject = 0xf4f7,

        /// <summary>
        /// Raspberry Pi (raspberry-pi)
        /// <para>Added in 5.6.0.</para>
        /// </summary>
        RaspberryPi = 0xf7bb,

        /// <summary>
        /// Ravelry (ravelry)
        /// <para>Added in 4.7.0, updated in 5.0.0.</para>
        /// </summary>
        Ravelry = 0xf2d9,

        /// <summary>
        /// React (react)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        React = 0xf41b,

        /// <summary>
        /// Reacteurope (reacteurope)
        /// <para>Added in 5.5.0, updated in 5.8.0.</para>
        /// </summary>
        Reacteurope = 0xf75d,

        /// <summary>
        /// Readme (readme)
        /// <para>Added in 5.0.10, updated in 5.0.9.</para>
        /// </summary>
        Readme = 0xf4d5,

        /// <summary>
        /// Rebel Alliance (rebel)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Rebel = 0xf1d0,

        /// <summary>
        /// Red River (red-river)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        RedRiver = 0xf3e3,

        /// <summary>
        /// Reddit Logo (reddit)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Reddit = 0xf1a1,

        /// <summary>
        /// Reddit Alien (reddit-alien)
        /// <para>Added in 4.5.0, updated in 5.0.0.</para>
        /// </summary>
        RedditAlien = 0xf281,

        /// <summary>
        /// Reddit Square (reddit-square)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        RedditSquare = 0xf1a2,

        /// <summary>
        /// Redhat (redhat)
        /// <para>Terms: linux, operating system, os</para>
        /// <para>Added in 5.6.0, updated in 5.8.2.</para>
        /// </summary>
        Redhat = 0xf7bc,

        /// <summary>
        /// Renren (renren)
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        Renren = 0xf18b,

        /// <summary>
        /// Replyd (replyd)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Replyd = 0xf3e6,

        /// <summary>
        /// Researchgate (researchgate)
        /// <para>Added in 5.0.11.</para>
        /// </summary>
        Researchgate = 0xf4f8,

        /// <summary>
        /// Resolving (resolving)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Resolving = 0xf3e7,

        /// <summary>
        /// Rev.Io (rev)
        /// <para>Added in 5.1.0, updated in 5.1.1 and 5.8.0.</para>
        /// </summary>
        Rev = 0xf5b2,

        /// <summary>
        /// Rocket.Chat (rocketchat)
        /// <para>Added in 5.0.0, updated in 5.4.2 and 5.8.0.</para>
        /// </summary>
        Rocketchat = 0xf3e8,

        /// <summary>
        /// Rockrms (rockrms)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Rockrms = 0xf3e9,

        /// <summary>
        /// Safari (safari)
        /// <para>Terms: browser</para>
        /// <para>Added in 4.4.0, updated in 5.0.0 and 5.12.0.</para>
        /// </summary>
        Safari = 0xf267,

        /// <summary>
        /// Salesforce (salesforce)
        /// <para>Added in 5.8.0.</para>
        /// </summary>
        Salesforce = 0xf83b,

        /// <summary>
        /// Sass (sass)
        /// <para>Added in 5.0.0, updated in 5.8.0.</para>
        /// </summary>
        Sass = 0xf41e,

        /// <summary>
        /// SCHLIX (schlix)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Schlix = 0xf3ea,

        /// <summary>
        /// Scribd (scribd)
        /// <para>Added in 4.5.0, updated in 5.0.0.</para>
        /// </summary>
        Scribd = 0xf28a,

        /// <summary>
        /// Searchengin (searchengin)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Searchengin = 0xf3eb,

        /// <summary>
        /// Sellcast (sellcast)
        /// <para>Terms: eercast</para>
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Sellcast = 0xf2da,

        /// <summary>
        /// Sellsy (sellsy)
        /// <para>Added in 4.3.0, updated in 5.0.0.</para>
        /// </summary>
        Sellsy = 0xf213,

        /// <summary>
        /// Servicestack (servicestack)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Servicestack = 0xf3ec,

        /// <summary>
        /// Shirts In Bulk (shirtsinbulk)
        /// <para>Added in 4.3.0, updated in 5.0.0 and 5.7.0.</para>
        /// </summary>
        Shirtsinbulk = 0xf214,

        /// <summary>
        /// Shopify (shopify)
        /// <para>Added in 5.12.1.</para>
        /// </summary>
        Shopify = 0xf957,

        /// <summary>
        /// Shopware (shopware)
        /// <para>Added in 5.1.0, updated in 5.8.0.</para>
        /// </summary>
        Shopware = 0xf5b5,

        /// <summary>
        /// Simplybuilt (simplybuilt)
        /// <para>Added in 4.3.0, updated in 5.0.0.</para>
        /// </summary>
        Simplybuilt = 0xf215,

        /// <summary>
        /// SISTRIX (sistrix)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Sistrix = 0xf3ee,

        /// <summary>
        /// Sith (sith)
        /// <para>Added in 5.0.12.</para>
        /// </summary>
        Sith = 0xf512,

        /// <summary>
        /// Sketch (sketch)
        /// <para>Terms: app, design, interface</para>
        /// <para>Added in 5.6.0, updated in 5.8.0.</para>
        /// </summary>
        Sketch = 0xf7c6,

        /// <summary>
        /// Skyatlas (skyatlas)
        /// <para>Added in 4.3.0, updated in 5.0.0 and 5.0.3.</para>
        /// </summary>
        Skyatlas = 0xf216,

        /// <summary>
        /// Skype (skype)
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        Skype = 0xf17e,

        /// <summary>
        /// Slack Logo (slack)
        /// <para>Terms: anchor, hash, hashtag</para>
        /// <para>Added in 4.1.0, updated in 5.0.0 and 5.7.0.</para>
        /// </summary>
        Slack = 0xf198,

        /// <summary>
        /// Slack Hashtag (slack-hash)
        /// <para>Terms: anchor, hash, hashtag</para>
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        SlackHash = 0xf3ef,

        /// <summary>
        /// Slideshare (slideshare)
        /// <para>Added in 4.2.0, updated in 5.0.0.</para>
        /// </summary>
        Slideshare = 0xf1e7,

        /// <summary>
        /// Snapchat (snapchat)
        /// <para>Added in 4.6.0, updated in 5.0.0.</para>
        /// </summary>
        Snapchat = 0xf2ab,

        /// <summary>
        /// Snapchat Ghost (snapchat-ghost)
        /// <para>Added in 4.6.0, updated in 5.0.0.</para>
        /// </summary>
        SnapchatGhost = 0xf2ac,

        /// <summary>
        /// Snapchat Square (snapchat-square)
        /// <para>Added in 4.6.0, updated in 5.0.0.</para>
        /// </summary>
        SnapchatSquare = 0xf2ad,

        /// <summary>
        /// Soundcloud (soundcloud)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Soundcloud = 0xf1be,

        /// <summary>
        /// Sourcetree (sourcetree)
        /// <para>Added in 5.6.0, updated in 5.8.0.</para>
        /// </summary>
        Sourcetree = 0xf7d3,

        /// <summary>
        /// Speakap (speakap)
        /// <para>Added in 5.0.0, updated in 5.4.0 and 5.8.0.</para>
        /// </summary>
        Speakap = 0xf3f3,

        /// <summary>
        /// Speaker Deck (speaker-deck)
        /// <para>Added in 5.8.0.</para>
        /// </summary>
        SpeakerDeck = 0xf83c,

        /// <summary>
        /// Spotify (spotify)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Spotify = 0xf1bc,

        /// <summary>
        /// Squarespace (squarespace)
        /// <para>Added in 5.1.0.</para>
        /// </summary>
        Squarespace = 0xf5be,

        /// <summary>
        /// Stack Exchange (stack-exchange)
        /// <para>Added in 4.0.0, updated in 5.0.0 and 5.0.3.</para>
        /// </summary>
        StackExchange = 0xf18d,

        /// <summary>
        /// Stack Overflow (stack-overflow)
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        StackOverflow = 0xf16c,

        /// <summary>
        /// Stackpath (stackpath)
        /// <para>Added in 5.8.2.</para>
        /// </summary>
        Stackpath = 0xf842,

        /// <summary>
        /// Staylinked (staylinked)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Staylinked = 0xf3f5,

        /// <summary>
        /// Steam (steam)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Steam = 0xf1b6,

        /// <summary>
        /// Steam Square (steam-square)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        SteamSquare = 0xf1b7,

        /// <summary>
        /// Steam Symbol (steam-symbol)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        SteamSymbol = 0xf3f6,

        /// <summary>
        /// Sticker Mule (sticker-mule)
        /// <para>Added in 5.0.0, updated in 5.7.0.</para>
        /// </summary>
        StickerMule = 0xf3f7,

        /// <summary>
        /// Strava (strava)
        /// <para>Added in 5.0.0, updated in 5.0.1, 5.7.0 and 5.8.0.</para>
        /// </summary>
        Strava = 0xf428,

        /// <summary>
        /// Stripe (stripe)
        /// <para>Added in 5.0.0, updated in 5.0.3.</para>
        /// </summary>
        Stripe = 0xf429,

        /// <summary>
        /// Stripe S (stripe-s)
        /// <para>Added in 5.0.1, updated in 5.8.0.</para>
        /// </summary>
        StripeS = 0xf42a,

        /// <summary>
        /// Studio Vinari (studiovinari)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Studiovinari = 0xf3f8,

        /// <summary>
        /// Stumbleupon Logo (stumbleupon)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Stumbleupon = 0xf1a4,

        /// <summary>
        /// Stumbleupon Circle (stumbleupon-circle)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        StumbleuponCircle = 0xf1a3,

        /// <summary>
        /// Superpowers (superpowers)
        /// <para>Added in 4.7.0, updated in 5.0.0.</para>
        /// </summary>
        Superpowers = 0xf2dd,

        /// <summary>
        /// Supple (supple)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Supple = 0xf3f9,

        /// <summary>
        /// Suse (suse)
        /// <para>Terms: linux, operating system, os</para>
        /// <para>Added in 5.6.0, updated in 5.8.0.</para>
        /// </summary>
        Suse = 0xf7d6,

        /// <summary>
        /// Swift (swift)
        /// <para>Added in 5.11.0.</para>
        /// </summary>
        Swift = 0xf8e1,

        /// <summary>
        /// Symfony (symfony)
        /// <para>Added in 5.8.0.</para>
        /// </summary>
        Symfony = 0xf83d,

        /// <summary>
        /// Teamspeak (teamspeak)
        /// <para>Added in 5.0.11, updated in 5.1.0 and 5.8.0.</para>
        /// </summary>
        Teamspeak = 0xf4f9,

        /// <summary>
        /// Telegram (telegram)
        /// <para>Added in 4.7.0, updated in 5.0.0.</para>
        /// </summary>
        Telegram = 0xf2c6,

        /// <summary>
        /// Telegram Plane (telegram-plane)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        TelegramPlane = 0xf3fe,

        /// <summary>
        /// Tencent Weibo (tencent-weibo)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        TencentWeibo = 0xf1d5,

        /// <summary>
        /// The Red Yeti (the-red-yeti)
        /// <para>Added in 5.3.0, updated in 5.7.0 and 5.8.0.</para>
        /// </summary>
        TheRedYeti = 0xf69d,

        /// <summary>
        /// Themeco (themeco)
        /// <para>Added in 5.1.0, updated in 5.8.0.</para>
        /// </summary>
        Themeco = 0xf5c6,

        /// <summary>
        /// Themeisle (themeisle)
        /// <para>Added in 4.6.0, updated in 5.0.0.</para>
        /// </summary>
        Themeisle = 0xf2b2,

        /// <summary>
        /// Think Peaks (think-peaks)
        /// <para>Added in 5.4.2, updated in 5.8.0.</para>
        /// </summary>
        ThinkPeaks = 0xf731,

        /// <summary>
        /// Trade Federation (trade-federation)
        /// <para>Added in 5.0.12.</para>
        /// </summary>
        TradeFederation = 0xf513,

        /// <summary>
        /// Trello (trello)
        /// <para>Terms: atlassian</para>
        /// <para>Added in 3.2.0, updated in 5.0.0 and 5.6.0.</para>
        /// </summary>
        Trello = 0xf181,

        /// <summary>
        /// Tripadvisor (tripadvisor)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        Tripadvisor = 0xf262,

        /// <summary>
        /// Tumblr (tumblr)
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        Tumblr = 0xf173,

        /// <summary>
        /// Tumblr Square (tumblr-square)
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        TumblrSquare = 0xf174,

        /// <summary>
        /// Twitch (twitch)
        /// <para>Added in 4.2.0, updated in 5.0.0 and 5.12.0.</para>
        /// </summary>
        Twitch = 0xf1e8,

        /// <summary>
        /// Twitter (twitter)
        /// <para>Terms: social network, tweet</para>
        /// <para>Added in 2.0.0, updated in 5.0.0.</para>
        /// </summary>
        Twitter = 0xf099,

        /// <summary>
        /// Twitter Square (twitter-square)
        /// <para>Terms: social network, tweet</para>
        /// <para>Added in 1.0.0, updated in 5.0.0.</para>
        /// </summary>
        TwitterSquare = 0xf081,

        /// <summary>
        /// Typo3 (typo3)
        /// <para>Added in 5.0.1, updated in 5.8.0.</para>
        /// </summary>
        Typo3 = 0xf42b,

        /// <summary>
        /// Uber (uber)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Uber = 0xf402,

        /// <summary>
        /// Ubuntu (ubuntu)
        /// <para>Terms: linux, operating system, os</para>
        /// <para>Added in 5.6.0.</para>
        /// </summary>
        Ubuntu = 0xf7df,

        /// <summary>
        /// Uikit (uikit)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Uikit = 0xf403,

        /// <summary>
        /// Umbraco (umbraco)
        /// <para>Added in 5.11.0.</para>
        /// </summary>
        Umbraco = 0xf8e8,

        /// <summary>
        /// Uniregistry (uniregistry)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Uniregistry = 0xf404,

        /// <summary>
        /// Unity 3D (unity)
        /// <para>Added in 5.12.0.</para>
        /// </summary>
        Unity = 0xf949,

        /// <summary>
        /// Untappd (untappd)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Untappd = 0xf405,

        /// <summary>
        /// UPS (ups)
        /// <para>Terms: United Parcel Service, package, shipping</para>
        /// <para>Added in 5.6.0, updated in 5.8.0.</para>
        /// </summary>
        Ups = 0xf7e0,

        /// <summary>
        /// USB (usb)
        /// <para>Added in 4.5.0, updated in 5.0.0.</para>
        /// </summary>
        Usb = 0xf287,

        /// <summary>
        /// United States Postal Service (usps)
        /// <para>Terms: american, package, shipping, usa</para>
        /// <para>Added in 5.6.0, updated in 5.8.0.</para>
        /// </summary>
        Usps = 0xf7e1,

        /// <summary>
        /// Us-Sunnah Foundation (ussunnah)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Ussunnah = 0xf407,

        /// <summary>
        /// Vaadin (vaadin)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Vaadin = 0xf408,

        /// <summary>
        /// Viacoin (viacoin)
        /// <para>Added in 4.3.0, updated in 5.0.0.</para>
        /// </summary>
        Viacoin = 0xf237,

        /// <summary>
        /// Video (viadeo)
        /// <para>Added in 4.6.0, updated in 5.0.0.</para>
        /// </summary>
        Viadeo = 0xf2a9,

        /// <summary>
        /// Video Square (viadeo-square)
        /// <para>Added in 4.6.0, updated in 5.0.0 and 5.7.0.</para>
        /// </summary>
        ViadeoSquare = 0xf2aa,

        /// <summary>
        /// Viber (viber)
        /// <para>Added in 5.0.0, updated in 5.0.3.</para>
        /// </summary>
        Viber = 0xf409,

        /// <summary>
        /// Vimeo (vimeo)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Vimeo = 0xf40a,

        /// <summary>
        /// Vimeo Square (vimeo-square)
        /// <para>Added in 4.0.0, updated in 5.0.0.</para>
        /// </summary>
        VimeoSquare = 0xf194,

        /// <summary>
        /// Vimeo (vimeo-v)
        /// <para>Terms: vimeo</para>
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        VimeoV = 0xf27d,

        /// <summary>
        /// Vine (vine)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Vine = 0xf1ca,

        /// <summary>
        /// VK (vk)
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        Vk = 0xf189,

        /// <summary>
        /// VNV (vnv)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Vnv = 0xf40b,

        /// <summary>
        /// Vue.Js (vuejs)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Vuejs = 0xf41f,

        /// <summary>
        /// Waze (waze)
        /// <para>Added in 5.8.0.</para>
        /// </summary>
        Waze = 0xf83f,

        /// <summary>
        /// Weebly (weebly)
        /// <para>Added in 5.1.0.</para>
        /// </summary>
        Weebly = 0xf5cc,

        /// <summary>
        /// Weibo (weibo)
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        Weibo = 0xf18a,

        /// <summary>
        /// Weixin (Wechat) (weixin)
        /// <para>Added in 4.1.0, updated in 5.0.0 and 5.0.3.</para>
        /// </summary>
        Weixin = 0xf1d7,

        /// <summary>
        /// What&apos;s App (whatsapp)
        /// <para>Added in 4.3.0, updated in 5.0.0.</para>
        /// </summary>
        Whatsapp = 0xf232,

        /// <summary>
        /// What&apos;s App Square (whatsapp-square)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        WhatsappSquare = 0xf40c,

        /// <summary>
        /// WHMCS (whmcs)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Whmcs = 0xf40d,

        /// <summary>
        /// Wikipedia W (wikipedia-w)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        WikipediaW = 0xf266,

        /// <summary>
        /// Windows (windows)
        /// <para>Terms: microsoft, operating system, os</para>
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        Windows = 0xf17a,

        /// <summary>
        /// Wix (wix)
        /// <para>Added in 5.1.0.</para>
        /// </summary>
        Wix = 0xf5cf,

        /// <summary>
        /// Wizards Of The Coast (wizards-of-the-coast)
        /// <para>Terms: Dungeons &amp; Dragons, d&amp;d, dnd, fantasy, game, gaming, tabletop</para>
        /// <para>Added in 5.4.0.</para>
        /// </summary>
        WizardsOfTheCoast = 0xf730,

        /// <summary>
        /// Wolf Pack Battalion (wolf-pack-battalion)
        /// <para>Added in 5.0.12, updated in 5.8.0.</para>
        /// </summary>
        WolfPackBattalion = 0xf514,

        /// <summary>
        /// Wordpress Logo (wordpress)
        /// <para>Added in 4.1.0, updated in 5.0.0.</para>
        /// </summary>
        Wordpress = 0xf19a,

        /// <summary>
        /// Wordpress Simple (wordpress-simple)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        WordpressSimple = 0xf411,

        /// <summary>
        /// Wpbeginner (wpbeginner)
        /// <para>Added in 4.6.0, updated in 5.0.0.</para>
        /// </summary>
        Wpbeginner = 0xf297,

        /// <summary>
        /// Wpexplorer (wpexplorer)
        /// <para>Added in 4.7.0, updated in 5.0.0.</para>
        /// </summary>
        Wpexplorer = 0xf2de,

        /// <summary>
        /// Wpforms (wpforms)
        /// <para>Added in 4.6.0, updated in 5.0.0.</para>
        /// </summary>
        Wpforms = 0xf298,

        /// <summary>
        /// Wpressr (wpressr)
        /// <para>Terms: rendact</para>
        /// <para>Added in 5.4.2.</para>
        /// </summary>
        Wpressr = 0xf3e4,

        /// <summary>
        /// Xbox (xbox)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Xbox = 0xf412,

        /// <summary>
        /// Xing (xing)
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        Xing = 0xf168,

        /// <summary>
        /// Xing Square (xing-square)
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        XingSquare = 0xf169,

        /// <summary>
        /// Y Combinator (y-combinator)
        /// <para>Added in 4.4.0, updated in 5.0.0.</para>
        /// </summary>
        YCombinator = 0xf23b,

        /// <summary>
        /// Yahoo Logo (yahoo)
        /// <para>Added in 4.1.0, updated in 5.0.0 and 5.0.3.</para>
        /// </summary>
        Yahoo = 0xf19e,

        /// <summary>
        /// Yammer (yammer)
        /// <para>Added in 5.8.0.</para>
        /// </summary>
        Yammer = 0xf840,

        /// <summary>
        /// Yandex (yandex)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        Yandex = 0xf413,

        /// <summary>
        /// Yandex International (yandex-international)
        /// <para>Added in 5.0.0.</para>
        /// </summary>
        YandexInternational = 0xf414,

        /// <summary>
        /// Yarn (yarn)
        /// <para>Added in 5.6.0.</para>
        /// </summary>
        Yarn = 0xf7e3,

        /// <summary>
        /// Yelp (yelp)
        /// <para>Added in 4.2.0, updated in 5.0.0, 5.7.0 and 5.8.0.</para>
        /// </summary>
        Yelp = 0xf1e9,

        /// <summary>
        /// Yoast (yoast)
        /// <para>Added in 4.6.0, updated in 5.0.0 and 5.0.3.</para>
        /// </summary>
        Yoast = 0xf2b1,

        /// <summary>
        /// Youtube (youtube)
        /// <para>Terms: film, video, youtube-play, youtube-square</para>
        /// <para>Added in 3.2.0, updated in 5.0.0.</para>
        /// </summary>
        Youtube = 0xf167,

        /// <summary>
        /// Youtube Square (youtube-square)
        /// <para>Added in 5.0.3.</para>
        /// </summary>
        YoutubeSquare = 0xf431,

        /// <summary>
        /// Zhihu (zhihu)
        /// <para>Added in 5.2.0.</para>
        /// </summary>
        Zhihu = 0xf63f,

    }
}
