namespace Geta.Epi.FontThumbnail
{
    /*https://github.com/denwilliams/FontAwesome-WindowsForms/blob/master/FontAwesomeIcons/IconType.cs*/
    public enum FontAwesome
    {
        Adjust = 0xf042,
        Adn = 0xf170,
        AlignCenter = 0xf037,
        AlignJustify = 0xf039,
        AlignLeft = 0xf036,
        AlignRight = 0xf038,
        Ambulance = 0xf0f9,
        Anchor = 0xf13d,
        Android = 0xf17b,
        AngleDoubleDown = 0xf103,
        AngleDoubleLeft = 0xf100,
        AngleDoubleRight = 0xf101,
        AngleDoubleUp = 0xf102,
        AngleDown = 0xf107,
        AngleLeft = 0xf104,
        AngleRight = 0xf105,
        AngleUp = 0xf106,
        Apple = 0xf179,
        Archive = 0xf187,
        ArrowCircleDown = 0xf0ab,
        ArrowCircleLeft = 0xf0a8,
        ArrowCircleODown = 0xf01a,
        ArrowCircleOLeft = 0xf190,
        ArrowCircleORight = 0xf18e,
        ArrowCircleOUp = 0xf01b,
        ArrowCircleRight = 0xf0a9,
        ArrowCircleUp = 0xf0aa,
        ArrowDown = 0xf063,
        ArrowLeft = 0xf060,
        ArrowRight = 0xf061,
        ArrowUp = 0xf062,
        Arrows = 0xf047,
        ArrowsAlt = 0xf0b2,
        ArrowsH = 0xf07e,
        ArrowsV = 0xf07d,
        Asterisk = 0xf069,
        Automobile = 0xf1b9,
        Backward = 0xf04a,
        Ban = 0xf05e,
        Bank = 0xf19c,
        BarChartO = 0xf080,
        Barcode = 0xf02a,
        Bars = 0xf0c9,
        Beer = 0xf0fc,
        Behance = 0xf1b4,
        BehanceSquare = 0xf1b5,
        Bell = 0xf0f3,
        BellO = 0xf0a2,
        Bitbucket = 0xf171,
        BitbucketSquare = 0xf172,
        Bitcoin = 0xf15a,
        Bold = 0xf032,
        Bolt = 0xf0e7,
        Bomb = 0xf1e2,
        Book = 0xf02d,
        Bookmark = 0xf02e,
        BookmarkO = 0xf097,
        Briefcase = 0xf0b1,
        Btc = 0xf15a,
        Bug = 0xf188,
        Building = 0xf1ad,
        BuildingO = 0xf0f7,
        Bullhorn = 0xf0a1,
        Bullseye = 0xf140,
        Cab = 0xf1ba,
        Calendar = 0xf073,
        CalendarO = 0xf133,
        Camera = 0xf030,
        CameraRetro = 0xf083,
        Car = 0xf1b9,
        CaretDown = 0xf0d7,
        CaretLeft = 0xf0d9,
        CaretRight = 0xf0da,
        CaretSquareODown = 0xf150,
        CaretSquareOLeft = 0xf191,
        CaretSquareORight = 0xf152,
        CaretSquareOUp = 0xf151,
        CaretUp = 0xf0d8,
        Certificate = 0xf0a3,
        Chain = 0xf0c1,
        ChainBroken = 0xf127,
        Check = 0xf00c,
        CheckCircle = 0xf058,
        CheckCircleO = 0xf05d,
        CheckSquare = 0xf14a,
        CheckSquareO = 0xf046,
        ChevronCircleDown = 0xf13a,
        ChevronCircleLeft = 0xf137,
        ChevronCircleRight = 0xf138,
        ChevronCircleUp = 0xf139,
        ChevronDown = 0xf078,
        ChevronLeft = 0xf053,
        ChevronRight = 0xf054,
        ChevronUp = 0xf077,
        Child = 0xf1ae,
        Circle = 0xf111,
        CircleO = 0xf10c,
        CircleONotch = 0xf1ce,
        CircleThin = 0xf1db,
        Clipboard = 0xf0ea,
        ClockO = 0xf017,
        Cloud = 0xf0c2,
        CloudDownload = 0xf0ed,
        CloudUpload = 0xf0ee,
        Cny = 0xf157,
        Code = 0xf121,
        CodeFork = 0xf126,
        Codepen = 0xf1cb,
        Coffee = 0xf0f4,
        Cog = 0xf013,
        Cogs = 0xf085,
        Columns = 0xf0db,
        Comment = 0xf075,
        CommentO = 0xf0e5,
        Comments = 0xf086,
        CommentsO = 0xf0e6,
        Compass = 0xf14e,
        Compress = 0xf066,
        Copy = 0xf0c5,
        CreditCard = 0xf09d,
        Crop = 0xf125,
        Crosshairs = 0xf05b,
        Css3 = 0xf13c,
        Cube = 0xf1b2,
        Cubes = 0xf1b3,
        Cut = 0xf0c4,
        Cutlery = 0xf0f5,
        Dashboard = 0xf0e4,
        Database = 0xf1c0,
        Dedent = 0xf03b,
        Delicious = 0xf1a5,
        Desktop = 0xf108,
        Deviantart = 0xf1bd,
        Digg = 0xf1a6,
        Dollar = 0xf155,
        DotCircleO = 0xf192,
        Download = 0xf019,
        Dribbble = 0xf17d,
        Dropbox = 0xf16b,
        Drupal = 0xf1a9,
        Edit = 0xf044,
        Eject = 0xf052,
        EllipsisH = 0xf141,
        EllipsisV = 0xf142,
        Empire = 0xf1d1,
        Envelope = 0xf0e0,
        EnvelopeO = 0xf003,
        EnvelopeSquare = 0xf199,
        Eraser = 0xf12d,
        Eur = 0xf153,
        Euro = 0xf153,
        Exchange = 0xf0ec,
        Exclamation = 0xf12a,
        ExclamationCircle = 0xf06a,
        ExclamationTriangle = 0xf071,
        Expand = 0xf065,
        ExternalLink = 0xf08e,
        ExternalLinkSquare = 0xf14c,
        Eye = 0xf06e,
        EyeSlash = 0xf070,
        Facebook = 0xf09a,
        FacebookSquare = 0xf082,
        FastBackward = 0xf049,
        FastForward = 0xf050,
        Fax = 0xf1ac,
        Female = 0xf182,
        FighterJet = 0xf0fb,
        File = 0xf15b,
        FileArchiveO = 0xf1c6,
        FileAudioO = 0xf1c7,
        FileCodeO = 0xf1c9,
        FileExcelO = 0xf1c3,
        FileImageO = 0xf1c5,
        FileMovieO = 0xf1c8,
        FileO = 0xf016,
        FilePdfO = 0xf1c1,
        FilePhotoO = 0xf1c5,
        FilePictureO = 0xf1c5,
        FilePowerpointO = 0xf1c4,
        FileSoundO = 0xf1c7,
        FileText = 0xf15c,
        FileTextO = 0xf0f6,
        FileVideoO = 0xf1c8,
        FileWordO = 0xf1c2,
        FileZipO = 0xf1c6,
        FilesO = 0xf0c5,
        Film = 0xf008,
        Filter = 0xf0b0,
        Fire = 0xf06d,
        FireExtinguisher = 0xf134,
        Flag = 0xf024,
        FlagCheckered = 0xf11e,
        FlagO = 0xf11d,
        Flash = 0xf0e7,
        Flask = 0xf0c3,
        Flickr = 0xf16e,
        FloppyO = 0xf0c7,
        Folder = 0xf07b,
        FolderO = 0xf114,
        FolderOpen = 0xf07c,
        FolderOpenO = 0xf115,
        Font = 0xf031,
        Forward = 0xf04e,
        Foursquare = 0xf180,
        FrownO = 0xf119,
        Gamepad = 0xf11b,
        Gavel = 0xf0e3,
        Gbp = 0xf154,
        Ge = 0xf1d1,
        Gear = 0xf013,
        Gears = 0xf085,
        Gift = 0xf06b,
        Git = 0xf1d3,
        GitSquare = 0xf1d2,
        Github = 0xf09b,
        GithubAlt = 0xf113,
        GithubSquare = 0xf092,
        Gittip = 0xf184,
        Glass = 0xf000,
        Globe = 0xf0ac,
        Google = 0xf1a0,
        GooglePlus = 0xf0d5,
        GooglePlusSquare = 0xf0d4,
        GraduationCap = 0xf19d,
        Group = 0xf0c0,
        HSquare = 0xf0fd,
        HackerNews = 0xf1d4,
        HandODown = 0xf0a7,
        HandOLeft = 0xf0a5,
        HandORight = 0xf0a4,
        HandOUp = 0xf0a6,
        HddO = 0xf0a0,
        Header = 0xf1dc,
        Headphones = 0xf025,
        Heart = 0xf004,
        HeartO = 0xf08a,
        History = 0xf1da,
        Home = 0xf015,
        HospitalO = 0xf0f8,
        Html5 = 0xf13b,
        Image = 0xf03e,
        Inbox = 0xf01c,
        Indent = 0xf03c,
        Info = 0xf129,
        InfoCircle = 0xf05a,
        Inr = 0xf156,
        Instagram = 0xf16d,
        Institution = 0xf19c,
        Italic = 0xf033,
        Joomla = 0xf1aa,
        Jpy = 0xf157,
        Jsfiddle = 0xf1cc,
        Key = 0xf084,
        KeyboardO = 0xf11c,
        Krw = 0xf159,
        Language = 0xf1ab,
        Laptop = 0xf109,
        Leaf = 0xf06c,
        Legal = 0xf0e3,
        LemonO = 0xf094,
        LevelDown = 0xf149,
        LevelUp = 0xf148,
        LifeBouy = 0xf1cd,
        LifeRing = 0xf1cd,
        LifeSaver = 0xf1cd,
        LightbulbO = 0xf0eb,
        Link = 0xf0c1,
        Linkedin = 0xf0e1,
        LinkedinSquare = 0xf08c,
        Linux = 0xf17c,
        List = 0xf03a,
        ListAlt = 0xf022,
        ListOl = 0xf0cb,
        ListUl = 0xf0ca,
        LocationArrow = 0xf124,
        Lock = 0xf023,
        LongArrowDown = 0xf175,
        LongArrowLeft = 0xf177,
        LongArrowRight = 0xf178,
        LongArrowUp = 0xf176,
        Magic = 0xf0d0,
        Magnet = 0xf076,
        MailForward = 0xf064,
        MailReply = 0xf112,
        MailReplyAll = 0xf122,
        Male = 0xf183,
        MapMarker = 0xf041,
        Maxcdn = 0xf136,
        Medkit = 0xf0Fa,
        MehO = 0xf11a,
        Microphone = 0xf130,
        MicrophoneSlash = 0xf131,
        Minus = 0xf068,
        MinusCircle = 0xf056,
        MinusSquare = 0xf146,
        MinusSquareO = 0xf147,
        Mobile = 0xf10b,
        MobilePhone = 0xf10b,
        Money = 0xf0d6,
        MoonO = 0xf186,
        MortarBoard = 0xf19d,
        Music = 0xf001,
        Navicon = 0xf0c9,
        Openid = 0xf19b,
        Outdent = 0xf03b,
        Pagelines = 0xf18c,
        PaperPlane = 0xf1d8,
        PaperPlaneO = 0xf1d9,
        Paperclip = 0xf0c6,
        Paragraph = 0xf1dd,
        Paste = 0xf0ea,
        Pause = 0xf04c,
        Paw = 0xf1b0,
        Pencil = 0xf040,
        PencilSquare = 0xf14b,
        PencilSquareO = 0xf044,
        Phone = 0xf095,
        PhoneSquare = 0xf098,
        Photo = 0xf03e,
        PictureO = 0xf03e,
        PiedPiper = 0xf1a7,
        PiedPiperAlt = 0xf1a8,
        PiedPiperSquare = 0xf1a7,
        Pinterest = 0xf0d2,
        PinterestSquare = 0xf0d3,
        Plane = 0xf072,
        Play = 0xf04b,
        PlayCircle = 0xf144,
        PlayCircleO = 0xf01d,
        Plus = 0xf067,
        PlusCircle = 0xf055,
        PlusSquare = 0xf0fe,
        PlusSquareO = 0xf196,
        PowerOff = 0xf011,
        Print = 0xf02f,
        PuzzlePiece = 0xf12e,
        QQ = 0xf1d6,
        Rrcode = 0xf029,
        Ruestion = 0xf128,
        RuestionCircle = 0xf059,
        RuoteLeft = 0xf10d,
        RuoteRight = 0xf10e,
        Ra = 0xf1d0,
        Random = 0xf074,
        Rebel = 0xf1d0,
        Recycle = 0xf1b8,
        Reddit = 0xf1a1,
        RedditSquare = 0xf1a2,
        Refresh = 0xf021,
        Renren = 0xf18b,
        Reorder = 0xf0c9,
        Repeat = 0xf01e,
        Reply = 0xf112,
        ReplyAll = 0xf122,
        Retweet = 0xf079,
        Rmb = 0xf157,
        Road = 0xf018,
        Rocket = 0xf135,
        RotateLeft = 0xf0e2,
        RotateRight = 0xf01e,
        Rouble = 0xf158,
        Rss = 0xf09e,
        RssSquare = 0xf143,
        Rub = 0xf158,
        Ruble = 0xf158,
        Rupee = 0xf156,
        Save = 0xf0c7,
        Scissors = 0xf0c4,
        Search = 0xf002,
        SearchMinus = 0xf010,
        SearchPlus = 0xf00e,
        Send = 0xf1d8,
        SendO = 0xf1d9,
        Share = 0xf064,
        ShareAlt = 0xf1e0,
        ShareAltSquare = 0xf1e1,
        ShareSquare = 0xf14d,
        ShareSquareO = 0xf045,
        Shield = 0xf132,
        ShoppingCart = 0xf07a,
        SignIn = 0xf090,
        SignOut = 0xf08b,
        Signal = 0xf012,
        Sitemap = 0xf0e8,
        Skype = 0xf17e,
        Slack = 0xf198,
        Sliders = 0xf1de,
        SmileO = 0xf118,
        Sort = 0xf0dc,
        SortAlphaAsc = 0xf15d,
        SortAlphaDesc = 0xf15e,
        SortAmountAsc = 0xf160,
        SortAmountDesc = 0xf161,
        SortAsc = 0xf0de,
        SortDesc = 0xf0dd,
        SortDown = 0xf0dd,
        SortNumericAsc = 0xf162,
        SortNumericDesc = 0xf163,
        SortUp = 0xf0de,
        Soundcloud = 0xf1be,
        SpaceShuttle = 0xf197,
        Spinner = 0xf110,
        Spoon = 0xf1b1,
        Spotify = 0xf1bc,
        Square = 0xf0c8,
        SquareO = 0xf096,
        StackExchange = 0xf18d,
        StackOverflow = 0xf16c,
        Star = 0xf005,
        StarHalf = 0xf089,
        StarHalfEmpty = 0xf123,
        StarHalfFull = 0xf123,
        StarHalfO = 0xf123,
        StarO = 0xf006,
        Steam = 0xf1b6,
        SteamSquare = 0xf1b7,
        StepBackward = 0xf048,
        StepForward = 0xf051,
        Stethoscope = 0xf0f1,
        Stop = 0xf04d,
        Strikethrough = 0xf0cc,
        Stumbleupon = 0xf1a4,
        StumbleuponCircle = 0xf1a3,
        Subscript = 0xf12c,
        Suitcase = 0xf0f2,
        SunO = 0xf185,
        Superscript = 0xf12b,
        Support = 0xf1cd,
        Table = 0xf0ce,
        Tablet = 0xf10a,
        Tachometer = 0xf0e4,
        Tag = 0xf02b,
        Tags = 0xf02c,
        Tasks = 0xf0ae,
        Taxi = 0xf1ba,
        TencentWeibo = 0xf1d5,
        Terminal = 0xf120,
        TextHeight = 0xf034,
        TextWidth = 0xf035,
        Th = 0xf00a,
        ThLarge = 0xf009,
        ThList = 0xf00b,
        ThumbTack = 0xf08d,
        ThumbsDown = 0xf165,
        ThumbsODown = 0xf088,
        ThumbsOUp = 0xf087,
        ThumbsUp = 0xf164,
        Ticket = 0xf145,
        Times = 0xf00d,
        TimesCircle = 0xf057,
        TimesCircleO = 0xf05c,
        Tint = 0xf043,
        ToggleDown = 0xf150,
        ToggleLeft = 0xf191,
        ToggleRight = 0xf152,
        ToggleUp = 0xf151,
        TrashO = 0xf014,
        Tree = 0xf1bb,
        Trello = 0xf181,
        Trophy = 0xf091,
        Truck = 0xf0d1,
        Try = 0xf195,
        Tumblr = 0xf173,
        TumblrSquare = 0xf174,
        TurkishLira = 0xf195,
        Twitter = 0xf099,
        TwitterSquare = 0xf081,
        Umbrella = 0xf0e9,
        Underline = 0xf0cd,
        Undo = 0xf0e2,
        University = 0xf19c,
        Unlink = 0xf127,
        Unlock = 0xf09c,
        UnlockAlt = 0xf13e,
        Unsorted = 0xf0dc,
        Upload = 0xf093,
        Usd = 0xf155,
        User = 0xf007,
        UserMd = 0xf0f0,
        Users = 0xf0c0,
        VideoCamera = 0xf03d,
        VimeoSquare = 0xf194,
        Vine = 0xf1ca,
        Vk = 0xf189,
        VolumeDown = 0xf027,
        VolumeOff = 0xf026,
        VolumeUp = 0xf028,
        Warning = 0xf071,
        Wechat = 0xf1d7,
        Weibo = 0xf18a,
        Weixin = 0xf1d7,
        Wheelchair = 0xf193,
        Windows = 0xf17a,
        Won = 0xf159,
        Wordpress = 0xf19a,
        Wrench = 0xf0ad,
        Xing = 0xf168,
        XingSquare = 0xf169,
        Yahoo = 0xf19e,
        Yen = 0xf157,
        Youtube = 0xf167,
        YoutubePlay = 0xf16a,
        YoutubeSquare = 0xf166,
    }



    /*  public static string FAGlass = "\uf000";
		public static string FAMusic = "\uf001";
		public static string FASearch = "\uf002";
		public static string FAEnvelopeO = "\uf003";
		public static string FAHeart = "\uf004";
		public static string FAStar = "\uf005";
		public static string FAStarO = "\uf006";
		public static string FAUser = "\uf007";
		public static string FAFilm = "\uf008";
		public static string FAThLarge = "\uf009";
		public static string FATh = "\uf00a";
		public static string FAThList = "\uf00b";
		public static string FACheck = "\uf00c";
		public static string FATimes = "\uf00d";
		public static string FASearchPlus = "\uf00e";
		public static string FASearchMinus = "\uf010";
		public static string FAPowerOff = "\uf011";
		public static string FASignal = "\uf012";
		public static string FACog = "\uf013";
		public static string FATrashO = "\uf014";
		public static string FAHome = "\uf015";
		public static string FAFileO = "\uf016";
		public static string FAClockO = "\uf017";
		public static string FARoad = "\uf018";
		public static string FADownload = "\uf019";
		public static string FAArrowCircleODown = "\uf01a";
		public static string FAArrowCircleOUp = "\uf01b";
		public static string FAInbox = "\uf01c";
		public static string FAPlayCircleO = "\uf01d";
		public static string FARepeat = "\uf01e";
		public static string FARefresh = "\uf021";
		public static string FAListAlt = "\uf022";
		public static string FALock = "\uf023";
		public static string FAFlag = "\uf024";
		public static string FAHeadphones = "\uf025";
		public static string FAVolumeOff = "\uf026";
		public static string FAVolumeDown = "\uf027";
		public static string FAVolumeUp = "\uf028";
		public static string FAQrcode = "\uf029";
		public static string FABarcode = "\uf02a";
		public static string FATag = "\uf02b";
		public static string FATags = "\uf02c";
		public static string FABook = "\uf02d";
		public static string FABookmark = "\uf02e";
		public static string FAPrint = "\uf02f";
		public static string FACamera = "\uf030";
		public static string FAFont = "\uf031";
		public static string FABold = "\uf032";
		public static string FAItalic = "\uf033";
		public static string FATextHeight = "\uf034";
		public static string FATextWidth = "\uf035";
		public static string FAAlignLeft = "\uf036";
		public static string FAAlignCenter = "\uf037";
		public static string FAAlignRight = "\uf038";
		public static string FAAlignJustify = "\uf039";
		public static string FAList = "\uf03a";
		public static string FAOutdent = "\uf03b";
		public static string FAIndent = "\uf03c";
		public static string FAVideoCamera = "\uf03d";
		public static string FAPictureO = "\uf03e";
		public static string FAPencil = "\uf040";
		public static string FAMapMarker = "\uf041";
		public static string FAAdjust = "\uf042";
		public static string FATint = "\uf043";
		public static string FAPencilSquareO = "\uf044";
		public static string FAShareSquareO = "\uf045";
		public static string FACheckSquareO = "\uf046";
		public static string FAArrows = "\uf047";
		public static string FAStepBackward = "\uf048";
		public static string FAFastBackward = "\uf049";
		public static string FABackward = "\uf04a";
		public static string FAPlay = "\uf04b";
		public static string FAPause = "\uf04c";
		public static string FAStop = "\uf04d";
		public static string FAForward = "\uf04e";
		public static string FAFastForward = "\uf050";
		public static string FAStepForward = "\uf051";
		public static string FAEject = "\uf052";
		public static string FAChevronLeft = "\uf053";
		public static string FAChevronRight = "\uf054";
		public static string FAPlusCircle = "\uf055";
		public static string FAMinusCircle = "\uf056";
		public static string FATimesCircle = "\uf057";
		public static string FACheckCircle = "\uf058";
		public static string FAQuestionCircle = "\uf059";
		public static string FAInfoCircle = "\uf05a";
		public static string FACrosshairs = "\uf05b";
		public static string FATimesCircleO = "\uf05c";
		public static string FACheckCircleO = "\uf05d";
		public static string FABan = "\uf05e";
		public static string FAArrowLeft = "\uf060";
		public static string FAArrowRight = "\uf061";
		public static string FAArrowUp = "\uf062";
		public static string FAArrowDown = "\uf063";
		public static string FAShare = "\uf064";
		public static string FAExpand = "\uf065";
		public static string FACompress = "\uf066";
		public static string FAPlus = "\uf067";
		public static string FAMinus = "\uf068";
		public static string FAAsterisk = "\uf069";
		public static string FAExclamationCircle = "\uf06a";
		public static string FAGift = "\uf06b";
		public static string FALeaf = "\uf06c";
		public static string FAFire = "\uf06d";
		public static string FAEye = "\uf06e";
		public static string FAEyeSlash = "\uf070";
		public static string FAExclamationTriangle = "\uf071";
		public static string FAPlane = "\uf072";
		public static string FACalendar = "\uf073";
		public static string FARandom = "\uf074";
		public static string FAComment = "\uf075";
		public static string FAMagnet = "\uf076";
		public static string FAChevronUp = "\uf077";
		public static string FAChevronDown = "\uf078";
		public static string FARetweet = "\uf079";
		public static string FAShoppingCart = "\uf07a";
		public static string FAFolder = "\uf07b";
		public static string FAFolderOpen = "\uf07c";
		public static string FAArrowsV = "\uf07d";
		public static string FAArrowsH = "\uf07e";
		public static string FABarChartO = "\uf080";
		public static string FATwitterSquare = "\uf081";
		public static string FAFacebookSquare = "\uf082";
		public static string FACameraRetro = "\uf083";
		public static string FAKey = "\uf084";
		public static string FACogs = "\uf085";
		public static string FAComments = "\uf086";
		public static string FAThumbsOUp = "\uf087";
		public static string FAThumbsODown = "\uf088";
		public static string FAStarHalf = "\uf089";
		public static string FAHeartO = "\uf08a";
		public static string FASignOut = "\uf08b";
		public static string FALinkedinSquare = "\uf08c";
		public static string FAThumbTack = "\uf08d";
		public static string FAExternalLink = "\uf08e";
		public static string FASignIn = "\uf090";
		public static string FATrophy = "\uf091";
		public static string FAGithubSquare = "\uf092";
		public static string FAUpload = "\uf093";
		public static string FALemonO = "\uf094";
		public static string FAPhone = "\uf095";
		public static string FASquareO = "\uf096";
		public static string FABookmarkO = "\uf097";
		public static string FAPhoneSquare = "\uf098";
		public static string FATwitter = "\uf099";
		public static string FAFacebook = "\uf09a";
		public static string FAGithub = "\uf09b";
		public static string FAUnlock = "\uf09c";
		public static string FACreditCard = "\uf09d";
		public static string FARss = "\uf09e";
		public static string FAHddO = "\uf0a0";
		public static string FABullhorn = "\uf0a1";
		public static string FABell = "\uf0f3";
		public static string FACertificate = "\uf0a3";
		public static string FAHandORight = "\uf0a4";
		public static string FAHandOLeft = "\uf0a5";
		public static string FAHandOUp = "\uf0a6";
		public static string FAHandODown = "\uf0a7";
		public static string FAArrowCircleLeft = "\uf0a8";
		public static string FAArrowCircleRight = "\uf0a9";
		public static string FAArrowCircleUp = "\uf0aa";
		public static string FAArrowCircleDown = "\uf0ab";
		public static string FAGlobe = "\uf0ac";
		public static string FAWrench = "\uf0ad";
		public static string FATasks = "\uf0ae";
		public static string FAFilter = "\uf0b0";
		public static string FABriefcase = "\uf0b1";
		public static string FAArrowsAlt = "\uf0b2";
		public static string FAUsers = "\uf0c0";
		public static string FALink = "\uf0c1";
		public static string FACloud = "\uf0c2";
		public static string FAFlask = "\uf0c3";
		public static string FAScissors = "\uf0c4";
		public static string FAFilesO = "\uf0c5";
		public static string FAPaperclip = "\uf0c6";
		public static string FAFloppyO = "\uf0c7";
		public static string FASquare = "\uf0c8";
		public static string FABars = "\uf0c9";
		public static string FAListUl = "\uf0ca";
		public static string FAListOl = "\uf0cb";
		public static string FAStrikethrough = "\uf0cc";
		public static string FAUnderline = "\uf0cd";
		public static string FATable = "\uf0ce";
		public static string FAMagic = "\uf0d0";
		public static string FATruck = "\uf0d1";
		public static string FAPinterest = "\uf0d2";
		public static string FAPinterestSquare = "\uf0d3";
		public static string FAGooglePlusSquare = "\uf0d4";
		public static string FAGooglePlus = "\uf0d5";
		public static string FAMoney = "\uf0d6";
		public static string FACaretDown = "\uf0d7";
		public static string FACaretUp = "\uf0d8";
		public static string FACaretLeft = "\uf0d9";
		public static string FACaretRight = "\uf0da";
		public static string FAColumns = "\uf0db";
		public static string FASort = "\uf0dc";
		public static string FASortAsc = "\uf0dd";
		public static string FASortDesc = "\uf0de";
		public static string FAEnvelope = "\uf0e0";
		public static string FALinkedin = "\uf0e1";
		public static string FAUndo = "\uf0e2";
		public static string FAGavel = "\uf0e3";
		public static string FATachometer = "\uf0e4";
		public static string FACommentO = "\uf0e5";
		public static string FACommentsO = "\uf0e6";
		public static string FABolt = "\uf0e7";
		public static string FASitemap = "\uf0e8";
		public static string FAUmbrella = "\uf0e9";
		public static string FAClipboard = "\uf0ea";
		public static string FALightbulbO = "\uf0eb";
		public static string FAExchange = "\uf0ec";
		public static string FACloudDownload = "\uf0ed";
		public static string FACloudUpload = "\uf0ee";
		public static string FAUserMd = "\uf0f0";
		public static string FAStethoscope = "\uf0f1";
		public static string FASuitcase = "\uf0f2";
		public static string FABellO = "\uf0a2";
		public static string FACoffee = "\uf0f4";
		public static string FACutlery = "\uf0f5";
		public static string FAFileTextO = "\uf0f6";
		public static string FABuildingO = "\uf0f7";
		public static string FAHospitalO = "\uf0f8";
		public static string FAAmbulance = "\uf0f9";
		public static string FAMedkit = "\uf0fa";
		public static string FAFighterJet = "\uf0fb";
		public static string FABeer = "\uf0fc";
		public static string FAHSquare = "\uf0fd";
		public static string FAPlusSquare = "\uf0fe";
		public static string FAAngleDoubleLeft = "\uf100";
		public static string FAAngleDoubleRight = "\uf101";
		public static string FAAngleDoubleUp = "\uf102";
		public static string FAAngleDoubleDown = "\uf103";
		public static string FAAngleLeft = "\uf104";
		public static string FAAngleRight = "\uf105";
		public static string FAAngleUp = "\uf106";
		public static string FAAngleDown = "\uf107";
		public static string FADesktop = "\uf108";
		public static string FALaptop = "\uf109";
		public static string FATablet = "\uf10a";
		public static string FAMobile = "\uf10b";
		public static string FACircleO = "\uf10c";
		public static string FAQuoteLeft = "\uf10d";
		public static string FAQuoteRight = "\uf10e";
		public static string FASpinner = "\uf110";
		public static string FACircle = "\uf111";
		public static string FAReply = "\uf112";
		public static string FAGithubAlt = "\uf113";
		public static string FAFolderO = "\uf114";
		public static string FAFolderOpenO = "\uf115";
		public static string FASmileO = "\uf118";
		public static string FAFrownO = "\uf119";
		public static string FAMehO = "\uf11a";
		public static string FAGamepad = "\uf11b";
		public static string FAKeyboardO = "\uf11c";
		public static string FAFlagO = "\uf11d";
		public static string FAFlagCheckered = "\uf11e";
		public static string FATerminal = "\uf120";
		public static string FACode = "\uf121";
		public static string FAReplyAll = "\uf122";
		public static string FAMailReplyAll = "\uf122";
		public static string FAStarHalfO = "\uf123";
		public static string FALocationArrow = "\uf124";
		public static string FACrop = "\uf125";
		public static string FACodeFork = "\uf126";
		public static string FAChainBroken = "\uf127";
		public static string FAQuestion = "\uf128";
		public static string FAInfo = "\uf129";
		public static string FAExclamation = "\uf12a";
		public static string FASuperscript = "\uf12b";
		public static string FASubscript = "\uf12c";
		public static string FAEraser = "\uf12d";
		public static string FAPuzzlePiece = "\uf12e";
		public static string FAMicrophone = "\uf130";
		public static string FAMicrophoneSlash = "\uf131";
		public static string FAShield = "\uf132";
		public static string FACalendarO = "\uf133";
		public static string FAFireExtinguisher = "\uf134";
		public static string FARocket = "\uf135";
		public static string FAMaxcdn = "\uf136";
		public static string FAChevronCircleLeft = "\uf137";
		public static string FAChevronCircleRight = "\uf138";
		public static string FAChevronCircleUp = "\uf139";
		public static string FAChevronCircleDown = "\uf13a";
		public static string FAHtml5 = "\uf13b";
		public static string FACss3 = "\uf13c";
		public static string FAAnchor = "\uf13d";
		public static string FAUnlockAlt = "\uf13e";
		public static string FABullseye = "\uf140";
		public static string FAEllipsisH = "\uf141";
		public static string FAEllipsisV = "\uf142";
		public static string FARssSquare = "\uf143";
		public static string FAPlayCircle = "\uf144";
		public static string FATicket = "\uf145";
		public static string FAMinusSquare = "\uf146";
		public static string FAMinusSquareO = "\uf147";
		public static string FALevelUp = "\uf148";
		public static string FALevelDown = "\uf149";
		public static string FACheckSquare = "\uf14a";
		public static string FAPencilSquare = "\uf14b";
		public static string FAExternalLinkSquare = "\uf14c";
		public static string FAShareSquare = "\uf14d";
		public static string FACompass = "\uf14e";
		public static string FACaretSquareODown = "\uf150";
		public static string FACaretSquareOUp = "\uf151";
		public static string FACaretSquareORight = "\uf152";
		public static string FAEur = "\uf153";
		public static string FAGbp = "\uf154";
		public static string FAUsd = "\uf155";
		public static string FAInr = "\uf156";
		public static string FAJpy = "\uf157";
		public static string FARub = "\uf158";
		public static string FAKrw = "\uf159";
		public static string FABtc = "\uf15a";
		public static string FAFile = "\uf15b";
		public static string FAFileText = "\uf15c";
		public static string FASortAlphaAsc = "\uf15d";
		public static string FASortAlphaDesc = "\uf15e";
		public static string FASortAmountAsc = "\uf160";
		public static string FASortAmountDesc = "\uf161";
		public static string FASortNumericAsc = "\uf162";
		public static string FASortNumericDesc = "\uf163";
		public static string FAThumbsUp = "\uf164";
		public static string FAThumbsDown = "\uf165";
		public static string FAYoutubeSquare = "\uf166";
		public static string FAYoutube = "\uf167";
		public static string FAXing = "\uf168";
		public static string FAXingSquare = "\uf169";
		public static string FAYoutubePlay = "\uf16a";
		public static string FADropbox = "\uf16b";
		public static string FAStackOverflow = "\uf16c";
		public static string FAInstagram = "\uf16d";
		public static string FAFlickr = "\uf16e";
		public static string FAAdn = "\uf170";
		public static string FABitbucket = "\uf171";
		public static string FABitbucketSquare = "\uf172";
		public static string FATumblr = "\uf173";
		public static string FATumblrSquare = "\uf174";
		public static string FALongArrowDown = "\uf175";
		public static string FALongArrowUp = "\uf176";
		public static string FALongArrowLeft = "\uf177";
		public static string FALongArrowRight = "\uf178";
		public static string FAApple = "\uf179";
		public static string FAWindows = "\uf17a";
		public static string FAAndroid = "\uf17b";
		public static string FALinux = "\uf17c";
		public static string FADribbble = "\uf17d";
		public static string FASkype = "\uf17e";
		public static string FAFoursquare = "\uf180";
		public static string FATrello = "\uf181";
		public static string FAFemale = "\uf182";
		public static string FAMale = "\uf183";
		public static string FAGittip = "\uf184";
		public static string FASunO = "\uf185";
		public static string FAMoonO = "\uf186";
		public static string FAArchive = "\uf187";
		public static string FABug = "\uf188";
		public static string FAVk = "\uf189";
		public static string FAWeibo = "\uf18a";
		public static string FARenren = "\uf18b";
		public static string FAPagelines = "\uf18c";
		public static string FAStackExchange = "\uf18d";
		public static string FAArrowCircleORight = "\uf18e";
		public static string FAArrowCircleOLeft = "\uf190";
		public static string FACaretSquareOLeft = "\uf191";
		public static string FADotCircleO = "\uf192";
		public static string FAWheelchair = "\uf193";
		public static string FAVimeoSquare = "\uf194";
		public static string FATry = "\uf195";
		public static string FAPlusSquareO = "\uf196"; */
}
 